/* Command Edition interface. All optional state is local; no accounts or telemetry. */
(function(G){'use strict';const R=G.RA,D=R.D,$=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Math.floor(n||0).toLocaleString('en-US'),clock=t=>Math.floor(t/60)+':'+Math.floor(t%60).toString().padStart(2,'0');
const names={hq:'建造场',power:'电力设施',barracks:'兵营',refinery:'采矿设施',factory:'战车工厂',radar:'雷达 / 空军指挥部',airfield:'空军指挥部',tech:'作战实验室',naval:'造船厂',robotcontrol:'控制中心'};
const read=(key,def)=>{try{return JSON.parse(localStorage.getItem(key))??def;}catch{return def;}};
const store=(key,data)=>{try{localStorage.setItem(key,JSON.stringify(data));return true;}catch{return false;}};
function option(v,label,selected){return `<option value="${esc(v)}"${String(v)===String(selected)?' selected':''}>${esc(label)}</option>`;}
function modal(id,title,body,cls=''){const div=document.createElement('div');div.id=id;div.className='modal hidden';div.setAttribute('role','dialog');div.innerHTML=`<section class="modal-panel ${cls}"><div class="panel-head"><div><div class="panel-kicker">COMMAND / OPERATIONS</div><h2>${esc(title)}</h2></div><button class="ghost" data-dismiss>关闭 ×</button></div>${body}</section>`;document.body.appendChild(div);div.querySelector('[data-dismiss]').onclick=()=>div.classList.add('hidden');return div;}
function mapPreview(canvas,id,slots=[]){
 if(!canvas)return;const c=canvas.getContext('2d'),W=canvas.width,H=canvas.height,scale=Math.min(W,H)/192;const ox=(W-192*scale)/2,oy=(H-192*scale)/2;
 c.clearRect(0,0,W,H);c.fillStyle='#131d24';c.fillRect(0,0,W,H);c.save();c.translate(ox,oy);c.scale(scale,scale);
 c.fillStyle=R.getMap(id).biome==='winter'?'#637777':id==='desert'?'#655747':'#344849';c.fillRect(0,0,192,192);
 if(id==='coast'){c.strokeStyle='#203c50';c.lineWidth=36;c.strokeRect(0,0,192,192);}
 c.strokeStyle='#a0b8b113';c.lineWidth=.4;for(let i=0;i<=192;i+=12){c.beginPath();c.moveTo(i,0);c.lineTo(i,192);c.moveTo(0,i);c.lineTo(192,i);c.stroke();}
 c.strokeStyle='#15232b';c.lineWidth=4;
 const lines=id==='urban'?[[0,96,192,96],[96,0,96,192],[66,0,66,192],[126,0,126,192],[0,66,192,66],[0,126,192,126]]:id==='fortress'?[[60,0,60,192],[132,0,132,192],[0,96,192,96]]:[[24,24,168,168],[24,168,168,24]];
 for(const l of lines){c.beginPath();c.moveTo(l[0],l[1]);c.lineTo(l[2],l[3]);c.stroke();}
 const objects=R.mapObjects(id);for(const o of objects.ores){c.fillStyle=o.gem?'#77d5c8':'#dbb875';c.beginPath();c.ellipse(o.x,o.z,4.2,2.8,-.5,0,Math.PI*2);c.fill();}
 for(const n of objects.neutrals){c.fillStyle=n.type==='oil'?'#f2e5ad':'#afbebd';c.fillRect(n.x-2,n.z-2,4,4);if(n.type==='oil'){c.strokeStyle='#f2e5ad';c.lineWidth=.7;c.strokeRect(n.x-3.5,n.z-3.5,7,7);}}
 const assignments=R.allocateSpawns(slots);for(let i=0;i<8;i++){const [x,z]=R.SPAWNS[i],owner=Object.keys(assignments).find(k=>assignments[k]===i),active=owner!==undefined;
 c.beginPath();c.arc(x,z,active?6:4.5,0,Math.PI*2);c.fillStyle=active?R.COLORS[slots[owner].color]:'#15232b';c.fill();c.strokeStyle=active?'#fff7dd':'#9fafac99';c.lineWidth=active?1:.7;c.stroke();c.font='bold 5.7px sans-serif';c.fillStyle=active?'#111c25':'#d5ddd7';c.textAlign='center';c.textBaseline='middle';c.fillText(String(i+1),x,z+.2);}
 c.restore();c.strokeStyle='#728c8960';c.lineWidth=1;c.strokeRect(.5,.5,W-1,H-1);
}
R.mapPreview=mapPreview;
R.initHeadquarters=function(){
 const app=R.app;let current='home',missionShown=null,noticeLog=[],chatLog=[],seatLock=false,replayData=null;
 const oldLayout=$('menu').querySelector('.menu-layout'),deploy=oldLayout.querySelector('.deploy-panel'),hero=oldLayout.querySelector('.hero');
 const shell=document.createElement('div');shell.id='headquarters';shell.innerHTML=`
 <aside class="hq-rail"><div class="hq-logo"><b>RA<span>Ⅱ</span></b><small>COMMAND EDITION</small></div><nav id="hq-nav">
 ${[['home','01','指挥中心'],['skirmish','02','遭遇战'],['training','03','训练与挑战'],['network','04','联机大厅'],['catalog','05','军械资料库'],['replays','06','录像与存档'],['settings','07','设置']].map(([id,n,t])=>`<button data-page="${id}"><small>${n}</small><span>${t}</span></button>`).join('')}
 </nav><div class="hq-rail-foot"><span class="live-dot"></span> 本地资产就绪<br><small>v${R.VERSION} / ${R.BUILD}<br>非官方学习项目</small></div></aside>
 <main id="hq-main"><header class="hq-header"><div><span class="hq-kicker">THEATER COMMAND SYSTEM</span><h2 id="page-title">指挥中心</h2></div><div class="hq-header-right"><span id="service-pill">离线可玩</span><button id="hq-fullscreen" class="ghost">⛶ 全屏</button></div></header>
 <section id="page-home" class="hq-page"><div class="home-copy"><div class="hq-kicker">RED ALERT II / A NEW DIMENSION</div><h1>重返<br><span>指挥席。</span></h1><p>从第一座发电厂，到最后一支装甲纵队。<br>你的下一条指令，决定战场走向。</p><div class="home-actions"><button class="primary" id="home-play">部署战场 ↗</button><button id="home-train">先来一场训练</button></div><div class="home-stats"><div><b>10</b><span>可选国家</span></div><div><b>06</b><span>战区布局</span></div><div><b>08</b><span>最大参战方</span></div></div></div>
 <div class="home-bottom"><article><small>01 / SOLO OPERATIONS</small><b>训练与挑战</b><p>五个教学目标，六波守卫挑战。</p><button data-go="training">进入训练中心 ↗</button></article><article><small>02 / MULTIPLAYER</small><b>与朋友共同指挥</b><p>房间码、逐席位设置与自动重连。</p><button data-go="network">打开联机大厅 ↗</button></article><article><small>03 / FIELD DATABASE</small><b>了解每一件武器</b><p>生产前置、能力说明和机制完成度。</p><button id="home-db">浏览军械库 ↗</button></article></div></section>
 <section id="page-deploy" class="hq-page hidden"><div class="deploy-grid"><div class="theater-column"><div class="theater-card"><div class="section-label">战区预览 <span id="map-recommend"></span></div><canvas id="map-preview" width="512" height="400"></canvas><div class="map-caption"><b id="map-caption-name"></b><span id="map-caption-desc"></span></div><div class="map-legend"><i class="ore"></i>矿石 <i class="gem"></i>宝石 <i class="oil"></i>油井 <span>数字为出生位置</span></div><div id="map-choices"></div></div>
 <div class="seat-card"><div class="section-label">作战席位 <button class="ghost tiny" id="reset-seats">按预设重置</button></div><div id="seat-editor"></div><div id="setup-error" role="status"></div><p class="micro-note">自动出生点按人数分配；双人优先对角。颜色和指定出生点不可重复。困难电脑有额外收入。</p></div>
 <div id="directory-card" class="seat-card hidden"><div class="section-label">当前服务器的公开房间 <button id="refresh-rooms" class="ghost tiny">刷新</button></div><div id="room-directory">连接服务器后查看房间。</div><div class="network-actions"><button id="copy-invite">复制邀请链接</button><button id="open-lobby-chat">房间聊天</button><button id="network-check">连接诊断</button></div><div id="diagnostic-output" class="micro-note"></div></div></div><div id="deployment-controls"></div></div></section>
 <section id="page-training" class="hq-page hidden"><div class="page-intro"><div class="hq-kicker">TRAIN / EXECUTE / ADAPT</div><h3>把操作练成直觉。</h3><p>每一关只解决一个问题。目标由游戏状态判定，不是勾选清单。</p></div><div id="training-grid"></div><article class="challenge-card"><div><div class="hq-kicker">SURVIVAL / SIX WAVES</div><h3>最后防线</h3><p>扩充基地，抵挡逐步增强的六波进攻。以当前选择的国家出战。</p></div><button id="survival-start" class="primary">开始守卫挑战 ↗</button></article></section>
 <section id="page-replays" class="hq-page hidden"><div class="page-intro"><div class="hq-kicker">OPERATIONS ARCHIVE</div><h3>复盘，才能看清下一步。</h3><p>本地录像支持播放、暂停、倍速、时间定位与切换视角。不同内容版本不会强行兼容。</p></div><div class="archive-actions"><button id="import-replay" class="primary">导入录像 .json</button><button id="continue-save">继续快速存档</button><button id="import-save">导入存档</button></div><div id="replay-library"></div><p class="micro-note">浏览器内最多保留最近 3 份录像。重要录像请导出文件；清理浏览器数据会删除本地记录。联机录像仅在对局结束后开放。</p></section>
 <section id="page-settings" class="hq-page hidden"><div class="page-intro"><div class="hq-kicker">PERSONAL COMMAND PROFILE</div><h3>让战场跟上你的手。</h3><p>键位、镜头与音效均保存在本机，不影响房间战斗规则。</p></div><div class="settings-grid"><button id="hq-camera"><b>镜头与手感</b><span>右键抓取 / 持续滚屏 / 缩放 / 边缘滚动</span></button><button id="hq-hotkeys"><b>键位设置</b><span>建筑选择 / 生产栏 / 编队 / 路径规划</span></button><button id="hq-help"><b>战地手册</b><span>操作说明、迷雾与特殊命令</span></button><button id="hq-about"><b>发行说明</b><span>已实现范围与尚待验收的内容</span></button></div><div class="profile-card"><label>联机昵称 <input id="nickname" maxlength="24" placeholder="指挥官"></label><label>界面大小 <select id="interface-scale"><option value="normal">标准</option><option value="large">大号文字</option></select></label><label>减少界面动画 <input id="reduce-motion" type="checkbox"></label></div></section>
 </main>`;
 $('menu').appendChild(shell);$('deployment-controls').appendChild(deploy);
 // Keep existing button IDs and bindings in a compact, accessible utility dock.
 const dock=document.createElement('div');dock.className='hidden';dock.id='legacy-dock';for(const b of hero.querySelectorAll('button'))dock.appendChild(b);$('menu').appendChild(dock);oldLayout.remove();$('menu').querySelector('.masthead').remove();$('menu').querySelector('.menu-footer').remove();
 deploy.querySelector('.panel-kicker').textContent='MATCH CONFIGURATION';deploy.querySelector('h3').textContent='作战参数';deploy.querySelector('.mode-tabs').classList.add('hidden');
 const networkSettings=document.createElement('div');networkSettings.className='field';networkSettings.innerHTML='<label>房间名称</label><input id="room-name" maxlength="40" placeholder="指挥官的房间"><label class="private-line"><input id="private-room" type="checkbox"> 仅通过房间码加入，不列入房间目录</label>';$('network-ui').prepend(networkSettings);
 const gate=document.createElement('div');gate.id='online-gate';gate.innerHTML='<b>公网服务未配置</b><p>此包没有预置已上线的中国公共服务器。局域网使用启动器；公网按钮不会连接到占位地址。</p><button id="online-entry">检查在线服务</button>';networkSettings.before(gate);
 const options=$('players');options.add(new Option('6方 · 开阔战线','6'));options.value='2';$('map').value='valley';$('fog-mode').value='double';
 $('nickname').value=read('ra3d-nickname','指挥官');$('nickname').onchange=()=>store('ra3d-nickname',$('nickname').value);
 const scale=read('ra3d-interface','normal');$('interface-scale').value=scale;document.body.classList.toggle('large-ui',scale==='large');$('interface-scale').onchange=()=>{document.body.classList.toggle('large-ui',$('interface-scale').value==='large');store('ra3d-interface',$('interface-scale').value);};
 $('reduce-motion').checked=read('ra3d-reduce-motion',false);document.body.classList.toggle('reduce-motion',$('reduce-motion').checked);$('reduce-motion').onchange=()=>{document.body.classList.toggle('reduce-motion',$('reduce-motion').checked);store('ra3d-reduce-motion',$('reduce-motion').checked);};
 app.setupSlots=R.defaultSlots(2,'usa','ffa');
 function resetSlots(){const n=+$('players').value;$('players').value=String(n);app.setupSlots=R.defaultSlots(n,$('nation').value,$('teams').value).map(s=>({...s,difficulty:$('difficulty').value}));renderSeats();renderPreview();if(app.net?.room&&app.net.host===app.net.player)app.net.send({type:'configure',config:app.config()});}
 function renderPreview(){const m=R.getMap($('map').value);mapPreview($('map-preview'),m.id,app.setupSlots||[]);$('map-caption-name').textContent=m.name+' / '+m.en;$('map-caption-desc').textContent=m.desc;$('map-recommend').textContent=m.recommended;document.querySelectorAll('[data-map]').forEach(b=>b.classList.toggle('active',b.dataset.map===m.id));}
 function renderSeats(){
  const net=app.net,network=current==='network'&&net?.room,slots=network?net.config.slots:app.setupSlots;
  $('seat-editor').innerHTML=`<div class="seat-head"><span>席位 / 状态</span><span>国家</span><span>队伍</span><span>颜色</span><span>出生点</span><span>难度</span></div>`+slots.map((s,i)=>{
   const member=network?net.members.find(m=>m.slot===i):null,editable=!network||net.host===net.player||i===net.player;
   const locked=editable?'':' disabled';const mine=!network?i===0:i===net.player;
   return `<div class="seat-row${s.closed?' closed':''}" data-seat="${i}"><div class="seat-person"><i style="background:${R.COLORS[s.color]}"></i><select data-field="kind"${member||mine?' disabled':locked}>${option('human',member?member.name:mine?'你 · 指挥官':'开放人类席位',s.kind)}${option('ai','电脑 '+(i+1),s.kind)}${option('closed','关闭席位',s.kind)}</select></div><select data-field="nation"${member&&!mine?' disabled':locked}>${R.NATIONS.map(n=>option(n.id,n.name,s.nation)).join('')}</select><select data-field="team"${locked}>${Array.from({length:8},(_,t)=>option(t,'队伍 '+(t+1),s.team)).join('')}</select><select data-field="color"${locked}>${['红','蓝','黄','紫','绿','橙','青','粉'].map((v,k)=>option(k,v,s.color)).join('')}</select><select data-field="spawn"${locked}>${option(-1,'自动',s.spawn)}${R.SPAWNS.map((v,k)=>option(k,String(k+1),s.spawn)).join('')}</select><select data-field="difficulty"${member||mine?' disabled':locked}>${[['easy','简单'],['normal','普通'],['hard','困难＋']].map(([v,l])=>option(v,l,s.difficulty)).join('')}</select></div>`;
  }).join('');
  for(const el of $('seat-editor').querySelectorAll('select'))el.onchange=()=>{const i=+el.closest('[data-seat]').dataset.seat,k=el.dataset.field,v=['team','color','spawn'].includes(k)?+el.value:el.value;if(network){net.send({type:'seat',slot:i,values:{[k]:v}});}else{app.setupSlots[i][k]=v;app.setupSlots[i].closed=app.setupSlots[i].kind==='closed';app.setupSlots[i].human=app.setupSlots[i].kind==='human';if(i===0&&k==='nation'){$('nation').value=v;$('nation').dispatchEvent(new Event('change'));}renderSeats();renderPreview();}};
  const valid=R.validateSetup({...app.config(),slots});$('setup-error').textContent=valid.ok?'开局检查通过 · 等价主矿 / 独立出生位':valid.error;$('setup-error').classList.toggle('valid',valid.ok);
 }
 $('map-choices').innerHTML=R.MAPS.map(m=>`<button data-map="${m.id}" title="${esc(m.desc)}"><span>${esc(m.name)}</span><small>${esc(m.tag)}</small></button>`).join('');
 for(const b of document.querySelectorAll('[data-map]'))b.onclick=()=>{if(current==='network'&&app.net?.room&&app.net.host!==app.net.player)return app.toast('地图由房主选择',true);$('map').value=b.dataset.map;$('map').dispatchEvent(new Event('change'));};
 for(const id of ['players','teams','difficulty'])$(id).addEventListener('change',resetSlots);
 for(const id of ['map','credits','fog-mode','startBase'])$(id).addEventListener('change',()=>{renderPreview();if(app.net?.room&&current==='network'&&app.net.host===app.net.player)app.net.send({type:'configure',config:app.config()});});
 $('nation').addEventListener('change',()=>{if(app.net?.room&&current==='network')app.net.send({type:'seat',values:{nation:$('nation').value}});else{app.setupSlots[0].nation=$('nation').value;renderSeats();}});
 $('reset-seats').onclick=resetSlots;
 app.onLobby=m=>{seatLock=true;app.setupSlots=JSON.parse(JSON.stringify(m.config.slots));for(const id of ['map','players','teams','difficulty','credits'])if(m.config[id]!==undefined)$(id).value=String(m.config[id]);$('startBase').value=String(m.config.startBase);if(m.you>=0)$('nation').value=m.config.slots[m.you].nation;renderSeats();renderPreview();seatLock=false;};
 function showPage(page){
  if(page==='catalog'){openCatalog();return;}if(app.playing)return;
  if(current==='network'&&page!=='network'&&app.net?.room){app.toast('离开联机大厅会保留房间连接；再次进入可以继续。');}
  current=page;app.page=page;for(const el of document.querySelectorAll('.hq-page'))el.classList.add('hidden');
  const deployPage=['skirmish','sandbox','network'].includes(page);$(deployPage?'page-deploy':'page-'+page)?.classList.remove('hidden');
  $('page-title').textContent=({home:'指挥中心',skirmish:'遭遇战部署',sandbox:'战术试验场',network:'联机大厅',training:'训练与挑战',replays:'录像与存档',settings:'设置'})[page]||page;
  for(const b of document.querySelectorAll('[data-page]'))b.classList.toggle('active',b.dataset.page===page||page==='sandbox'&&b.dataset.page==='skirmish');
  if(deployPage){app.setMode(page==='network'?'network':page==='sandbox'?'sandbox':'skirmish');$('directory-card').classList.toggle('hidden',page!=='network');renderSeats();renderPreview();$('mode-description').textContent=page==='network'?'房主调整席位和地图，所有玩家准备后开始。支持两分钟断线恢复。':page==='sandbox'?'自由部署全部定义对象；沙盒不判胜。':'消灭敌方全部建筑与基地车获胜。先侦察，再决定扩张或进攻。';}
  if(page==='replays')renderArchive();
 }
 app.showPage=showPage;app.returnHome=()=>{missionShown=null;showPage('home');$('connection-banner').classList.add('hidden');$('mission-panel').classList.add('hidden');$('replay-bar').classList.add('hidden');};
 for(const b of document.querySelectorAll('[data-page]'))b.onclick=()=>showPage(b.dataset.page);
 for(const b of document.querySelectorAll('[data-go]'))b.onclick=()=>showPage(b.dataset.go);
 $('home-play').onclick=()=>showPage('skirmish');$('home-train').onclick=()=>showPage('training');$('home-db').onclick=()=>openCatalog();
 const sandboxButton=document.createElement('button');sandboxButton.id='sandbox-entry';sandboxButton.className='ghost';sandboxButton.textContent='切换战术沙盒';sandboxButton.onclick=()=>showPage(current==='sandbox'?'skirmish':'sandbox');deploy.querySelector('.panel-head').appendChild(sandboxButton);
 $('hq-fullscreen').onclick=()=>$('menu-fullscreen').click();$('hq-camera').onclick=()=>$('menu-camera').click();$('hq-hotkeys').onclick=()=>{if($('hotkeys-open'))$('hotkeys-open').click();else{app.openHotkeys?.();$('hotkeys-modal').classList.remove('hidden');}};$('hq-help').onclick=()=>$('help-modal').classList.remove('hidden');
 modal('about-modal','指挥版 1.0.0',`<p>本次改动：公平出生与主矿、六张数据地图、独立作战席位、五个训练目标、六波挑战、基础战术 AI、三阵营部分机制补充、录像回放与联机断线恢复。</p><p>所有模型与音效为程序化资产，部分高级单位仍为近似实现。不是原版 1.001 的完整数值复刻。</p><p><b>本包没有已上线的中国公共服务器。</b>公网部署、安全运维与真实跨运营商测试仍须完成。局域网运行依赖启动器中的 Node 运行环境；首次引导可能需要联网获取官方运行时。</p><p>无账号、无统计上报、无自动连接第三方服务器。服务器只在显式启动时运行。</p><p class="micro-note">build ${R.BUILD} · rules ${R.RULES_HASH} · maps ${R.MAP_HASH}</p>`,'wide-panel');$('hq-about').onclick=()=>$('about-modal').classList.remove('hidden');
 // Training and challenge flow.
 const completed=()=>read('ra3d-training',[]);
 function trainingCards(){$('training-grid').innerHTML=R.TRAINING.map((t,i)=>`<article class="training-card"><div class="training-number">0${i+1}</div><div class="training-content"><small>${completed().includes(t.id)?'已完成 ✓':'基础训练 / '+R.nation(t.nation).name}</small><h3>${esc(t.title)}</h3><p>${esc(t.objective)}</p><button data-training="${t.id}">进入训练 ↗</button></div></article>`).join('');for(const b of document.querySelectorAll('[data-training]'))b.onclick=()=>startTraining(b.dataset.training);}
 function startTraining(id){const t=R.TRAINING.find(x=>x.id===id);if(!t)return;missionShown=null;const cfg={...app.config(),players:2,map:'valley',nation:t.nation,training:id,sandbox:false,teams:'ffa',fogMode:'none',startBase:true,credits:20000,slots:R.defaultSlots(2,t.nation)};app.startLocal(cfg);}
 $('survival-start').onclick=()=>{missionShown=null;app.startLocal({...app.config(),players:2,map:'fortress',challenge:'survival',teams:'ffa',slots:R.defaultSlots(2,$('nation').value),sandbox:false,startBase:true,fogMode:'double'});};trainingCards();
 // HUD additions use the existing renderer, command path and input rules.
 $('hud').insertAdjacentHTML('beforeend',`<div id="connection-banner" class="hidden" role="status"></div><section id="mission-panel" class="hidden"><div class="hq-kicker" id="mission-kicker">FIELD OBJECTIVE</div><b id="mission-title"></b><p id="mission-text"></p><span id="mission-progress"></span><button id="mission-next" class="hidden">下一项训练 ↗</button><button id="mission-back">退出训练</button></section><div id="selection-groups"></div><div id="hud-utilities"><button id="hud-alerts">事件</button><button id="hud-chat">聊天</button><button id="hud-marker">标记位置</button><button id="hud-replay-export">保存录像</button></div><div id="replay-bar" class="hidden"><b>录像</b><button id="replay-pause">暂停</button><select id="replay-speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="3">3×</option></select><input id="replay-seek" type="range" min="0" max="100" value="0"><span id="replay-time"></span><select id="replay-view"></select><button id="replay-exit">退出</button></div>`);
 $('mission-back').onclick=()=>{app.quit();showPage('training');};$('mission-next').onclick=()=>{const index=R.TRAINING.findIndex(t=>t.id===app.state?.mission?.id);app.quit();if(index<4)startTraining(R.TRAINING[index+1].id);else showPage('training');};
 modal('alerts-modal','战地事件','<div id="alert-history"></div><p class="micro-note">记录本机已收到的通知，不暴露未侦察敌军信息。</p>','wide-panel');
 app.logNotice=(text,error)=>{noticeLog.push({text,error,time:app.state?.time||0});noticeLog=noticeLog.slice(-60);};
 $('hud-alerts').onclick=()=>{$('alert-history').innerHTML=noticeLog.slice().reverse().map(n=>`<div class="alert-row"><time>${clock(n.time)}</time><span>${esc(n.text)}</span></div>`).join('')||'<p>尚无事件。</p>';$('alerts-modal').classList.remove('hidden');};
 modal('chat-modal','房间通讯','<div id="chat-history" role="log" aria-live="polite"></div><form id="chat-form"><label><input id="chat-team" type="checkbox">仅队友</label><input id="chat-text" maxlength="180" autocomplete="off" placeholder="输入消息，Enter发送"><button class="primary">发送</button></form>','wide-panel');
 function showChat(){if(!app.net?.room)return app.toast('联机房间内才能聊天');$('chat-modal').classList.remove('hidden');$('chat-text').focus();}
 $('hud-chat').onclick=showChat;$('open-lobby-chat').onclick=showChat;$('chat-form').onsubmit=e=>{e.preventDefault();if(app.net?.send({type:'chat',text:$('chat-text').value,team:$('chat-team').checked}))$('chat-text').value='';};
 $('hud-marker').onclick=()=>{if(!app.net?.room)return app.toast('位置标记供联机队友使用');app.net.send({type:'marker',x:app.renderer.target.x,z:app.renderer.target.z});};
 window.addEventListener('keydown',e=>{if(e.code==='Enter'&&app.playing&&app.net&&!app.plan&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&document.querySelectorAll('.modal:not(.hidden)').length===0){e.preventDefault();showChat();}});
 app.netStatus=(text,status)=>{const bad=['reconnecting','error','connecting'].includes(status);$('connection-banner').textContent=text;$('connection-banner').classList.toggle('hidden',!app.playing||!bad);$('service-pill').textContent=status==='connected'?'房间服务已连接':'离线可玩';};
 app.onNetwork=m=>{
  if(m.type==='rooms'){$('room-directory').innerHTML=m.rooms.length?m.rooms.map(r=>`<button class="room-row" data-room="${r.code}"><span><b>${esc(r.name)}</b><small>${esc(R.getMap(r.map).name)} · ${r.players}/${r.seats} 人</small></span><code>${r.code} →</code></button>`).join(''):'<p class="empty-state">暂时没有公开房间。你可以创建第一个房间。</p>';for(const b of document.querySelectorAll('[data-room]'))b.onclick=()=>{$('room-code').value=b.dataset.room;app.connect('join');};}
  if(m.type==='chat'){chatLog.push(m);chatLog=chatLog.slice(-80);$('chat-history').innerHTML=chatLog.map(c=>`<p><b>${esc(c.name)}${c.team?' [队友]':''}</b><span>${esc(c.text)}</span></p>`).join('');$('chat-history').scrollTop=$('chat-history').scrollHeight;if($('chat-modal').classList.contains('hidden'))app.toast(m.name+'：'+m.text);}
  if(m.type==='marker'){app.pings=app.pings||[];app.pings.push({...m,expires:performance.now()+6000});app.toast((app.state?.players[m.slot]?.name||'队友')+' 标记了位置');app.lastAlert={x:m.x,z:m.z};}
 };
 $('refresh-rooms').onclick=()=>{if(app.net?.connected)app.net.send({type:'list'});else app.connect('list');};
 $('copy-invite').onclick=async()=>{
  if(!app.net?.room)return app.toast('请先进入房间',true);
  const u=new URL(app.net.url);u.protocol=u.protocol==='wss:'?'https:':'http:';u.pathname='/';u.search='';
  if(['127.0.0.1','localhost','[::1]'].includes(u.hostname))try{
   const info=await(await fetch(new URL('/api/server',u),{signal:AbortSignal.timeout(3000)})).json();
   if(info.addresses?.length){const lan=new URL(info.addresses[0]);u.hostname=lan.hostname;u.port=lan.port;}
  }catch{}
  u.search='room='+app.net.room;const link=u.href;$('diagnostic-output').textContent='邀请链接：'+link;
  try{await navigator.clipboard.writeText(link);app.toast('邀请链接已复制。朋友打开后点击加入即可。');}catch{app.toast('邀请链接已显示在下方，可手动复制。');}
 };
 $('network-check').onclick=async()=>{
  const out=$('diagnostic-output');out.textContent='正在检查当前服务器…';try{const u=new URL($('server-url').value);u.protocol=u.protocol==='wss:'?'https:':'http:';u.pathname='/api/server';u.search='';const res=await fetch(u,{signal:AbortSignal.timeout(4000)});const info=await res.json();out.textContent=`服务 ${info.version} / ${info.content===R.CONTENT_HASH?'内容一致':'内容版本不一致'} / ${info.public?'公网模式':'私人局域网模式'}。${info.addresses?.length?'局域网邀请地址：'+info.addresses.join('　'):''}`;}catch{out.textContent='HTTP诊断不可达或被浏览器跨域限制。检查启动器是否仍开着、主机IP、防火墙、同一网络或访客Wi-Fi隔离。';}
 };
 $('online-entry').onclick=async()=>{
  if(location.protocol==='file:'){$('online-gate').querySelector('p').textContent='此离线包没有已部署的公共服务器。请先通过局域网启动器打开游戏；公网接入需要实际运行的项目服务器。';return;}
  try{const res=await fetch('./online.json',{signal:AbortSignal.timeout(3000)});const cfg=await res.json();const endpoint=cfg.endpoints?.find(e=>e.enabled&&e.url?.startsWith('wss://'));if(!endpoint){$('online-gate').querySelector('p').textContent='未配置有效在线节点；没有向任何第三方服务器发送连接。';return;}$('server-url').value=endpoint.url;app.connect('list');}catch{$('online-gate').querySelector('p').textContent='在线服务配置不可用。局域网不受影响。';}
 };
 // Encyclopedia: inspect the actual current definitions, including prerequisites and caveats.
 modal('details-modal','单位详情','<div id="unit-details"></div>','wide-panel');
 const originalCatalog=app.catalog;function openCatalog(){originalCatalog($('catalog-search').value);$('catalog-modal').classList.remove('hidden');bindCatalog();}
 function bindCatalog(){const q=$('catalog-search').value.toLowerCase(),list=R.defs().filter(d=>!q||`${d.name} ${d.id} ${R.FACTIONS[d.faction]?.name} ${d.description||''}`.toLowerCase().includes(q));[...$('catalog-grid').children].forEach((el,i)=>{el.tabIndex=0;el.setAttribute('role','button');el.onclick=()=>showDetails(list[i]);el.onkeydown=e=>{if(e.code==='Enter')showDetails(list[i]);};});}
 $('catalog-search').addEventListener('input',bindCatalog);$('menu-catalog').onclick=openCatalog;
 function showDetails(d){
  const counters=({bullet:'擅长轻步兵，面对重装甲效率有限。',cannon:'装甲对抗与地面火力，留意反坦克步兵。',psi:'争夺可控制目标；机械免疫、控制上限和反步兵火力是主要限制。',missile:'远程导弹，是否对空以属性为准。',magnet:'牵引载具，依赖其他单位保护。',tesla:'电击火力，适合混合兵种掩护。',prism:'远程能量火力，注意被绕后突击。'})[d.weapon]||'结合射程、护甲与特殊能力安排兵种搭配。';
  const modes=d.id==='ifv'?'乘员改变武器：工程师提供维修，普通步兵提供反步兵火力，反坦克兵提供导弹。':d.id==='s_tesla'?'附近磁暴步兵增强火力；两名充能者可在缺电时维持线圈作战。':d.ability==='slave'?'独立移动与采矿。矿站被毁后解除绑定。':'';
  $('unit-details').innerHTML=`<div class="detail-title">${app.icon(d)}<div><div class="hq-kicker">${esc(d.id)}</div><h3>${esc(d.name)}</h3><p>${esc(R.FACTIONS[d.faction]?.name||'中立')} / ${esc(d.kind)}</p></div></div><div class="detail-metrics"><div><b>$${money(d.cost)}</b><small>费用</small></div><div><b>${d.hp}</b><small>生命</small></div><div><b>${d.damage||'—'}</b><small>基础伤害</small></div><div><b>${d.range||'—'}</b><small>射程</small></div></div><h3>生产链</h3><p>${(d.requires||[]).map(r=>esc(names[r]||r)).join(' → ')||'基础生产设施'}${d.nation?' · 限定国家：'+R.nation(d.nation).name:''}${d.sandboxOnly?' · 当前仅用于沙盒或特殊生成':''}</p><h3>战术与能力</h3><p>${esc(d.description||counters)}</p><p>${esc(modes||counters)}</p><h3>当前实现说明</h3><p>使用独立模拟实体与程序化三维模型。具体数字为本工程数值，不代表已核验原版规则。高级机制仍有近似实现。</p>`;
  $('details-modal').classList.remove('hidden');
 }
 app.lockReason=d=>{const missing=d.requires.filter(r=>!app.own().some(e=>D[e.type].role===r||r==='radar'&&D[e.type].role==='airfield'));if(missing.length)return'需要：'+missing.map(r=>names[r]||r).join('、');if(d.water&&app.state?.map!=='coast')return'当前战区没有海域';const role=d.kind==='building'?'hq':d.kind==='infantry'?'barracks':d.kind==='ship'?'naval':d.producer||'factory';return'需要生产设施：'+(names[role]||role);};
 // Recorder and archive, with explicit bounded storage.
 const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.className='hidden';file.id='replay-input';document.body.appendChild(file);
 app.onReplay=data=>{replayData=data;app.download('RA3D_'+R.VERSION+'_'+Date.now()+'.replay.json',JSON.stringify(data),'application/json');if(JSON.stringify(data).length<2000000){let list=read('ra3d-replays',[]);list.unshift({id:Date.now(),map:data.initial.cfg.map,date:new Date().toLocaleString(),ticks:data.endTick,data});if(!store('ra3d-replays',list.slice(0,3)))app.toast('浏览器空间不足，录像文件已导出');}app.toast('录像已导出');};
 function exportReplay(){if(app.net){app.net.send({type:'replay'});return;}app.worker?.postMessage({type:'exportReplay'});}
 $('hud-replay-export').onclick=exportReplay;
 function playReplay(data){try{new R.Replay(data);if(app.net)app.disconnect();app.replayMode=true;app.beginView();app.state=null;app.replayMode=true;app.createWorker().postMessage({type:'replay',data});$('sandbox-toggle').classList.add('hidden');$('netbadge').textContent='REPLAY / LOCAL';$('replay-view').innerHTML=data.initial.players.map((p,i)=>option(i,p.name||'玩家 '+(i+1),0)).join('');$('replay-bar').classList.remove('hidden');$('replay-seek').max=data.endTick;$('replay-speed').value='1';}catch(e){app.toast('录像读取失败：'+e.message,true);}}
 app.playReplay=playReplay;
 file.onchange=async()=>{try{const f=file.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('录像超过20MB');playReplay(JSON.parse(await f.text()));}catch(e){app.toast(e.message,true);}file.value='';};$('import-replay').onclick=()=>file.click();
 $('replay-pause').onclick=()=>{const paused=!app.state?.replay?.paused;app.worker?.postMessage({type:'pause',paused});};$('replay-speed').onchange=()=>app.worker?.postMessage({type:'speed',speed:+$('replay-speed').value});$('replay-seek').onchange=()=>{app.toast('正在定位录像…');app.worker?.postMessage({type:'seekReplay',tick:+$('replay-seek').value});};$('replay-view').onchange=()=>{app.selected.clear();app.worker?.postMessage({type:'replayView',player:+$('replay-view').value});};$('replay-exit').onclick=()=>{app.quit();showPage('replays');};
 function renderArchive(){const list=read('ra3d-replays',[]);$('replay-library').innerHTML=list.length?list.map(r=>`<article class="replay-entry"><div><b>${esc(R.getMap(r.map).name)}</b><span>${esc(r.date)} · ${clock(r.ticks*.1)}</span></div><button data-watch="${r.id}">播放</button><button data-delete="${r.id}" class="ghost">删除</button></article>`).join(''):'<div class="empty-state">还没有本地录像。对局内点击“保存录像”，或导入已有文件。</div>';for(const b of document.querySelectorAll('[data-watch]'))b.onclick=()=>playReplay(list.find(r=>String(r.id)===b.dataset.watch).data);for(const b of document.querySelectorAll('[data-delete]'))b.onclick=()=>{store('ra3d-replays',list.filter(r=>String(r.id)!==b.dataset.delete));renderArchive();};}
 $('continue-save').onclick=()=>{try{const data=JSON.parse(localStorage.getItem('ra3d-save'));if(!data)throw Error('没有快速存档');app.startLocal(data.cfg);app.loadSave(data);}catch(e){app.toast(e.message,true);}};
 const saveInput=document.createElement('input');saveInput.type='file';saveInput.accept='.json';saveInput.className='hidden';document.body.appendChild(saveInput);$('import-save').onclick=()=>saveInput.click();saveInput.onchange=async()=>{try{const f=saveInput.files[0];if(f.size>10000000)throw Error('存档超过10MB');const data=JSON.parse(await f.text());R.Sim.load(data);app.startLocal(data.cfg);app.loadSave(data);}catch(e){app.toast(e.message,true);}saveInput.value='';};
 // Results use only the authoritative end-state. Hidden enemy economy is not shown mid-game.
 const results=document.createElement('div');results.id='extended-results';$('result-menu').before(results);
 app.afterResult=s=>{results.innerHTML=`<div class="result-table"><div class="result-row heading"><span>指挥官</span><span>摧毁</span><span>损失</span><span>收入</span><span>支出</span></div>${s.players.filter(p=>!p.closed).map(p=>`<div class="result-row"><span style="border-left:3px solid ${p.color}">${esc(p.name)}${p.team===s.winner?' ★':''}</span><span>${p.kills}</span><span>${p.lost}</span><span>${p.earned===undefined?'待结束':money(p.earned)}</span><span>${p.spent===undefined?'待结束':money(p.spent)}</span></div>`).join('')}</div><canvas id="economy-chart" width="640" height="100"></canvas><div class="result-buttons"><button id="result-rematch" class="primary">再来一局</button><button id="result-swap">换边再战</button><button id="result-recording">导出录像</button></div>`;
  $('result-rematch').onclick=()=>{if(app.net)app.net.send({type:'rematch'});else{const cfg=app.lastConfig||s.cfg;app.quit();app.startLocal(cfg);}};
  $('result-swap').disabled=!!app.net;$('result-swap').onclick=()=>{const cfg=JSON.parse(JSON.stringify(app.lastConfig||s.cfg));cfg.slots=R.resolveSlots(cfg);const assignments=R.allocateSpawns(cfg.slots),a=assignments[0],other=Object.keys(assignments).find(i=>+i!==0);if(other!==undefined){cfg.slots[0].spawn=assignments[other];cfg.slots[other].spawn=a;}app.quit();app.startLocal(cfg);};$('result-recording').onclick=exportReplay;
  const chart=$('economy-chart'),c=chart.getContext('2d'),history=s.p.history||[];c.clearRect(0,0,640,100);c.fillStyle='#829b9f';c.font='12px sans-serif';c.fillText('己方资金曲线',8,15);if(history.length>1){const max=Math.max(...history.map(v=>v.credits||0),1);c.beginPath();history.forEach((h,i)=>{const x=8+i/(history.length-1)*624,y=88-(h.credits||0)/max*60;if(!i)c.moveTo(x,y);else c.lineTo(x,y);});c.strokeStyle='#dac899';c.lineWidth=2;c.stroke();}
 };
 let selectionStamp='';
 app.upgradeUI=s=>{
  $('hud-chat').disabled=!app.net;$('hud-marker').disabled=!app.net;$('hud-replay-export').classList.toggle('hidden',!!s.replay);
  $('replay-bar').classList.toggle('hidden',!s.replay);if(s.replay){$('replay-pause').textContent=s.replay.paused?'播放':'暂停';$('replay-time').textContent=clock(s.time)+' / '+clock(s.replay.end*.1);if(document.activeElement!==$('replay-seek'))$('replay-seek').value=s.tick;}
  const mission=s.mission,wave=s.wave;$('mission-panel').classList.toggle('hidden',!mission&&!wave||!!s.replay);
  if(mission){const t=R.TRAINING.find(x=>x.id===mission.id);$('mission-title').textContent=t?.title||'训练';$('mission-text').textContent=mission.completed?'训练完成。你已经掌握本关操作。':(t?.objective||'')+' '+(t?.tip||'');$('mission-progress').textContent=mission.completed?'OBJECTIVE COMPLETE':'目标进行中';$('mission-next').classList.toggle('hidden',!mission.completed);$('mission-back').textContent='退出训练';if(mission.completed&&missionShown!==mission.id){missionShown=mission.id;store('ra3d-training',[...new Set([...completed(),mission.id])]);trainingCards();app.toast('训练完成：'+t.title);}}
  else if(wave){$('mission-title').textContent='最后防线 · 第 '+wave.number+' / 6 波';$('mission-text').textContent='守住基地，清除所有六波敌军。';$('mission-progress').textContent='下一波 '+Math.max(0,Math.ceil(wave.next-s.time))+' 秒';$('mission-next').classList.add('hidden');$('mission-back').textContent='退出挑战';}
  const selected=s.entities.filter(e=>app.selected.has(e.id)),stamp=selected.map(e=>e.id+':'+(e.manifest||[]).map(p=>p.id).join(',')).join('|');
  if(stamp!==selectionStamp){selectionStamp=stamp;const types=[...new Set(selected.map(e=>e.type))];$('selection-groups').innerHTML=types.length>1?types.map(t=>`<button data-group-type="${t}">${esc(D[t].name)} ×${selected.filter(e=>e.type===t).length}</button>`).join(''):'';
   const carrier=selected.length===1?selected[0]:null;if(carrier?.manifest?.length)$('selection-groups').innerHTML+=carrier.manifest.map(p=>`<button data-passenger="${p.id}" title="单独卸载">↓ ${esc(D[p.type].name)}</button>`).join('');
   for(const b of $('selection-groups').querySelectorAll('[data-group-type]'))b.onclick=()=>{app.selected=new Set(selected.filter(e=>e.type===b.dataset.groupType).map(e=>e.id));app.selectionUI();};for(const b of $('selection-groups').querySelectorAll('[data-passenger]'))b.onclick=()=>app.command({type:'unloadOne',carrier:carrier.id,id:+b.dataset.passenger});
  }
  if(selected.length===1){const e=selected[0];const extra=[e.weaponMode,e.flightPhase?({combat:'空中作战',returning:'返航',rearming:'停机补弹',holding:'盘旋等待','no-airfield':'缺少机场'})[e.flightPhase]||e.flightPhase:null,e.chargers?.length?'磁暴充能 ×'+e.chargers.length:null,e.lifted>0?'受到磁电牵引':null,e.bomb?.time>0?'定时炸弹 '+e.bomb.time.toFixed(1)+'s':null].filter(Boolean);if(extra.length)$('selection-extra').textContent=extra.join(' · ');}
 };
 renderSeats();renderPreview();showPage('home');
 // Invitation links contain only a room code; never put recovery credentials in URLs.
 if(location.protocol!=='file:'){const code=new URLSearchParams(location.search).get('room');if(code&&/^[A-F0-9]{6}$/i.test(code)){$('room-code').value=code.toUpperCase();showPage('network');app.toast('邀请已就绪。选择国家并点击加入。');}}
 try{const saved=JSON.parse(sessionStorage.getItem('ra3d-resume'));if(saved&&Date.now()-saved.at<120000){const button=document.createElement('button');button.textContent='恢复房间 '+saved.code;button.onclick=()=>{$('server-url').value=saved.url;showPage('network');app.connect('resume',saved);};$('home-play').after(button);}}catch{}
};
})(globalThis);
