/* Public relay adapter. MQTT forwards opaque ciphertext; a browser Worker hosts the
 * same RoomService used on LAN. Invitations pin the host's ECDH key. Each guest
 * has a different AES-GCM channel, so other guests cannot decrypt its fog state.
 * This is private casual play, not a trusted dedicated-server anti-cheat system. */
(function(G){'use strict';const R=G.RA,enc=new TextEncoder(),dec=new TextDecoder();
R.DEFAULT_BROKER='wss://broker.emqx.io:8084/mqtt';
R.BROKER_ALTERNATIVES=[R.DEFAULT_BROKER,'wss://broker-cn.emqx.io:8084/mqtt','wss://broker.hivemq.com:8884/mqtt','wss://test.mosquitto.org:8081/mqtt'];
const PREFIX='ra3d-command/100',MAX=12*1024*1024;
const random=n=>crypto.getRandomValues(new Uint8Array(n));
const b64=a=>{let s='';for(let i=0;i<a.length;i+=16384)s+=String.fromCharCode(...a.subarray(i,i+16384));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');};
const un64=s=>{if(typeof s!=='string'||s.length>MAX*1.5||!/^[A-Za-z0-9_-]*$/.test(s))throw Error('数据编码无效');return Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));};
const token=n=>b64(random(n));
function parseInvite(value){let s=String(value||'').trim();if(s.includes('#ra='))s=s.split('#ra=')[1];if(!s.startsWith('RA1.')||s.length>1600)throw Error('请粘贴以 RA1. 开头的完整邀请口令');let o;try{o=JSON.parse(dec.decode(un64(s.slice(4))));}catch{throw Error('邀请口令损坏或不完整');}
 if(o.v!==1||typeof o.r!=='string'||!/^[A-Za-z0-9_-]{22}$/.test(o.r)||un64(o.k).length!==32||un64(o.h).length!==65)throw Error('邀请参数无效');const u=new URL(o.b);if(u.protocol!=='wss:'&&!(u.protocol==='ws:'&&['127.0.0.1','localhost','[::1]'].includes(u.hostname)))throw Error('邀请包含不安全的节点地址');if(u.username||u.password||u.hash||o.c&&!/^[A-F0-9]{6}$/.test(o.c))throw Error('邀请地址或房间码无效');return o;
}
async function keypair(){if(!G.crypto?.subtle)throw Error('此页面无法使用加密功能。请双击本地 PLAY.html，或通过 localhost/HTTPS 打开。');return crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);}
async function derive(pair,publicKey,invite,id){const pub=await crypto.subtle.importKey('raw',un64(publicKey),{name:'ECDH',namedCurve:'P-256'},false,[]),bits=await crypto.subtle.deriveBits({name:'ECDH',public:pub},pair.privateKey,256),raw=await crypto.subtle.importKey('raw',bits,'HKDF',false,['deriveKey']);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt:un64(invite.k),info:enc.encode(invite.r+'/'+id)},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function streamBytes(stream,max=MAX){const reader=stream.getReader(),parts=[];let len=0;try{while(true){const {done,value}=await reader.read();if(done)break;len+=value.length;if(len>max)throw Error('解压数据超出限制');parts.push(value);}}catch(e){await reader.cancel();throw e;}return R.MQTTCodec.join(...parts);}
async function seal(channel,topic,message){let bytes=enc.encode(JSON.stringify(message));if(bytes.length>MAX)throw Error('同步数据超过12MB');let compressed=0;if(bytes.length>1024&&typeof CompressionStream!=='undefined'){const zipped=await streamBytes(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip')));if(zipped.length<bytes.length){bytes=zipped;compressed=1;}}
 const n=++channel.tx,iv=random(12),aad=enc.encode(topic+'|'+n+'|'+compressed),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},channel.key,bytes);return JSON.stringify({s:n,z:compressed,i:b64(iv),d:b64(new Uint8Array(cipher))});
}
async function open(channel,topic,payload){if(payload.length>MAX*1.4)throw Error('加密消息过大');const v=JSON.parse(payload);if(!Number.isSafeInteger(v.s)||v.s<=channel.rx||v.s<1||![0,1].includes(v.z))throw Error('过期或重复的加密消息');const iv=un64(v.i);if(iv.length!==12)throw Error('加密随机数无效');let bytes=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:enc.encode(topic+'|'+v.s+'|'+v.z)},channel.key,un64(v.d)));
 if(v.z){if(typeof DecompressionStream==='undefined')throw Error('浏览器不支持解压');bytes=await streamBytes(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')));}if(bytes.length>MAX)throw Error('消息过大');const out=JSON.parse(dec.decode(bytes));channel.rx=v.s;return out;
}
R.RelayCrypto={b64,un64,parseInvite,keypair,derive,seal,open};
// Runs inside the hosting browser's Worker, separate from its rendering thread.
function hostWorker(){let service=null,links=new Map(),acc=0,last=performance.now(),flush=0,relayPaused=false;const add=id=>{let p=links.get(id);if(p&&!p.closed)return p;const ws={readyState:1,bufferedAmount:0,ip:id,send:s=>postMessage({type:'to',id,message:JSON.parse(s)}),close:()=>{ws.readyState=3;service.left(p);postMessage({type:'closed',id});}};p=service.add(ws);links.set(id,p);return p;};
 onmessage=e=>{try{const m=e.data;if(m.type==='init'){service=new RA.RoomService({limits:{rooms:1,connections:16,perIP:16},log:()=>{}});return;}if(!service)return;if(m.type==='relayPaused'){relayPaused=!!m.value;acc=0;last=performance.now();}if(m.type==='message')service.handle(add(m.id),m.message);if(m.type==='detach'){const p=links.get(m.id);if(p){p.ws.readyState=3;service.left(p);}}if(m.type==='resyncAll'){for(const p of links.values())if(!p.closed){p.base=null;p.pending=null;service.handle(p,{type:'resync'});}}if(m.type==='backup'){const room=[...service.rooms.values()][0];if(room?.sim)postMessage({type:'backup',data:room.sim.save()});}}catch(error){postMessage({type:'fault',message:error.message});}};
 setInterval(()=>{const now=performance.now();acc+=Math.min(.5,(now-last)/1000);last=now;if(!service)return;if(relayPaused){acc=0;return;}let n=0;while(acc>=RA.STEP&&n++<5){service.advance();acc-=RA.STEP;}if(now-flush>=250){service.flush();flush=now;}},25);setInterval(()=>service?.sweep(),5000);
}
R.MqttRoomClient=class{
 constructor(url,action,payload,receive,status){this.url=url;this.action=action;this.payload=payload;this.receive=receive;this.status=status;this.transport='mqtt';this.connected=false;this.seq=0;this.retry=0;this.intentional=false;this.channels=new Map();this.fragments=new Map();this.rooms=new Map();this.bytesOut=0;this.bytesIn=0;this.peerId=token(16);this.rxChain=Promise.resolve();this._running=true;this.ready=this.init().catch(e=>{if(!this.intentional&&!this._closing){this.status(e.message,'error');this.failure=e.message;this.worker?.terminate();}});}
 async init(){this.pair=await keypair();if(this.intentional||this._closing)return;this.publicKey=b64(new Uint8Array(await crypto.subtle.exportKey('raw',this.pair.publicKey)));if(this.intentional||this._closing)return;this.hosting=this.action==='create';
  if(this.hosting)this.inv={v:1,b:this.url,r:token(16),k:token(32),h:this.publicKey};
  else if(['join','watch','resume'].includes(this.action)){this.inv=parseInvite(this.payload.code);this.invite=this.payload.code;this.url=this.inv.b;this.channel={key:await derive(this.pair,this.inv.h,this.inv,this.peerId),tx:0,rx:0,queue:Promise.resolve()};}
  this.baseTopic=this.inv?PREFIX+'/room/'+this.inv.r:null;
  if(this.hosting){const source=document.getElementById('data-source').textContent+'\n'+document.getElementById('sim-source').textContent+'\n'+document.getElementById('wire-source').textContent+'\n'+document.getElementById('authority-source').textContent+'\n('+hostWorker.toString()+')();';const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));this.worker=new Worker(url);URL.revokeObjectURL(url);this.worker.onmessage=e=>this.fromWorker(e.data);this.worker.onerror=e=>this.status('房主模拟异常：'+e.message,'error');this.worker.postMessage({type:'init'});}
  await this.connect(false);
 }
 async connect(reconnect){if(this.intentional)return;this.status(reconnect?'节点连接中断，正在恢复加密通道…':'正在连接公共 MQTT 节点…','connecting');
  const choices=!reconnect&&this.hosting?[this.url,...R.BROKER_ALTERNATIVES.filter(u=>u!==this.url)]:[this.url];let lastError;
  for(const url of choices){if(this.intentional)return;this.url=url;if(this.inv)this.inv.b=url;
   const wire=new R.MQTTWire(url,{timeout:7000,will:this.hosting?{topic:PREFIX+'/lobby/'+this.inv.r,payload:''}:undefined,message:(topic,data)=>{if(this.mqtt!==wire||this.intentional)return;this.bytesIn+=data.length;this.rxChain=this.rxChain.then(()=>this.onPacket(topic,data)).catch(()=>{this.rejected=(this.rejected||0)+1;});},close:()=>{if(this.mqtt===wire&&!this.intentional&&this._connectedOnce)this.disconnected();}});this.mqtt=wire;
   try{await wire.connect();if(this.intentional){wire.close();return;}const topics=this.hosting?[this.baseTopic+'/join/+',this.baseTopic+'/up/+']:this.inv?[this.baseTopic+'/down/'+this.peerId]:[PREFIX+'/lobby/+'];await wire.subscribe(topics);if(this.intentional)return;this._connectedOnce=true;this.retry=0;clearTimeout(this.retryTimer);
    if(this.hosting){this.connected=true;this.status('公共中转已连接 · 你是模拟主机，请保持页面开启','connected');if(reconnect){this.worker.postMessage({type:'detach',id:'self'});this.toWorker('self',{type:'hello',...R.netIdentity()});this.toWorker('self',{type:'resume',code:this.room,token:this.token,...R.netIdentity()});this.worker.postMessage({type:'relayPaused',value:false});this.worker.postMessage({type:'resyncAll'});this.lastAdvert=0;this.advertise();}else{this.toWorker('self',{type:'hello',...R.netIdentity()});this.toWorker('self',{type:'create',...this.payload,...R.netIdentity()});}}
    else if(this.inv){this.connected=false;await this.handshake();clearInterval(this.handshakeTimer);this.handshakeTimer=setInterval(()=>{if(!this.connected&&this.mqtt?.connected)this.handshake().catch(()=>{});},4000);clearTimeout(this.joinTimer);this.joinTimer=setTimeout(()=>{if(!this.connected)this.status('已连接节点，但房主未响应。确认房主在线、口令完整且使用同一版本。','error');},14000);}
    else{this.connected=true;this.status('公共房间目录已连接 · 仅显示当前节点','connected');}
    clearInterval(this.heartbeat);this.heartbeat=setInterval(()=>{if(this.connected&&this.room)this.send({type:'ping',at:Date.now()});if(this.hosting)this.advertise();if(!this.inv)this.emitRooms();if(this.inv&&!this.hosting&&this.connected&&Date.now()-(this.lastHost||Date.now())>18000){this.connected=false;this.status('房主暂时无响应，停止下令并等待恢复。关闭房主页面会结束房间。','reconnecting');this.handshake().catch(()=>{});}},6000);return;
   }catch(e){lastError=e;wire.close();if(this.mqtt===wire)this.mqtt=null;this.status('节点不可用：'+new URL(url).hostname+'，尝试下一个候选…','connecting');}
  }
  if(reconnect){this.retry++;if(!this.disconnectedAt)this.disconnectedAt=Date.now();if(Date.now()-this.disconnectedAt<115000){this.retryTimer=setTimeout(()=>this.connect(true),Math.min(6000,1000*this.retry));return;}}
  throw Error((lastError?.message||'节点连接失败')+'。可更换节点后重新创建房间；邀请已绑定节点，不会静默切换到其他房间。');
 }
 disconnected(){if(this.intentional||this._closing||this._retrying)return;if(this.hosting)this.worker?.postMessage({type:'relayPaused',value:true});this.connected=false;this.baseline=null;this.disconnectedAt=this.disconnectedAt||Date.now();this.status('中转连接中断，暂时停止下令并自动重连…','reconnecting');this._retrying=true;clearTimeout(this.retryTimer);this.retryTimer=setTimeout(async()=>{this._retrying=false;try{await this.connect(true);}catch(e){this.status(e.message,'error');}},1500);}
 async handshake(){if(this.intentional||!this.channel||!this.mqtt?.connected)return;const msg={...R.netIdentity(),...this.payload,type:this.token?'resume':this.action==='watch'?'watch':'join',code:this.inv.c,token:this.token};const topic=this.baseTopic+'/join/'+this.peerId;
  this.channel.queue=this.channel.queue.catch(()=>{}).then(async()=>{const data=await seal(this.channel,topic,msg);this.publish(topic,JSON.stringify({p:this.publicKey,e:data}),1);});return this.channel.queue;
 }
 toWorker(id,message){this.worker?.postMessage({type:'message',id,message});}
 fromWorker(m){if(this.intentional)return;if(m.type==='fault')return this.status(m.message,'error');if(m.type==='backup'){R.app?.download('RA3D_host_backup.json',JSON.stringify(m.data),'application/json');return;}if(m.type==='closed'){if(m.id!=='self'){const ch=this.channels.get(m.id);if(ch)ch.active=false;}return;}if(m.type!=='to')return;if(m.id!=='self'&&m.message.type==='error'&&!this.started){const ch=this.channels.get(m.id);if(ch)ch.active=false;}
  if(m.id==='self')this.accept(m.message);else{const ch=this.channels.get(m.id);if(ch)this.transmit(ch,this.baseTopic+'/down/'+m.id,m.message);}
 }
 publish(topic,value,qos=0,retained=false){if(!this.mqtt?.connected||this.intentional)return false;const bytes=typeof value==='string'?enc.encode(value):value;this.bytesOut+=bytes.length;if(bytes.length<=24000)return this.mqtt.publish(topic,bytes,qos,retained);if(retained||bytes.length>MAX*1.4)throw Error('消息超出分片限制');const data=b64(bytes),size=22000,n=Math.ceil(data.length/size),id=token(12);for(let i=0;i<n;i++)if(!this.mqtt.publish(topic,JSON.stringify({f:id,i,n,d:data.slice(i*size,(i+1)*size)}),qos,false))return false;return true;}
 async publishAsync(topic,value,qos=0){const bytes=enc.encode(value);if(bytes.length<=24000)return this.publish(topic,value,qos);if(bytes.length>MAX*1.4)throw Error('同步数据过大');const data=b64(bytes),size=22000,n=Math.ceil(data.length/size),id=token(12);if(n>512)throw Error('分片数量超出限制');this.bytesOut+=bytes.length;
  for(let i=0;i<n;i++){let waited=0;while(this.mqtt?.connected&&(this.mqtt.pending.size>70||this.mqtt.ws.bufferedAmount>256000)&&waited<15000){await new Promise(r=>setTimeout(r,25));waited+=25;}if(!this.mqtt?.connected||this.intentional||waited>=15000)return false;if(!this.mqtt.publish(topic,JSON.stringify({f:id,i,n,d:data.slice(i*size,(i+1)*size)}),qos,false))return false;}return true;
 }
 transmit(channel,topic,msg){if(!this.mqtt?.connected||this.intentional)return false;const state=msg.type==='state'||msg.type==='delta';if(channel.queued>12&&state)return false;if(channel.queued>80)return false;channel.queued=(channel.queued||0)+1;channel.queue=(channel.queue||Promise.resolve()).catch(()=>{}).then(async()=>{if(!this.mqtt?.connected)return;const payload=await seal(channel,topic,msg);if(!await this.publishAsync(topic,payload,state?0:1)&&!state)this.status('发送通道拥堵，请等待连接恢复','reconnecting');}).catch(e=>{this.status('发送失败：'+e.message,'error');}).finally(()=>channel.queued--);return true;}
 async onPacket(topic,bytes){if(this.intentional||bytes.length>262144)return;let payload=dec.decode(bytes),outer;try{outer=JSON.parse(payload);}catch{return;}
  const now=Date.now();for(const [key,a]of this.fragments)if(now-a.at>15000)this.fragments.delete(key);
  if(outer.f){if(!/^[A-Za-z0-9_-]{16}$/.test(outer.f)||!Number.isInteger(outer.n)||outer.n<2||outer.n>512||!Number.isInteger(outer.i)||outer.i<0||outer.i>=outer.n||typeof outer.d!=='string'||outer.d.length>22000)return;const key=topic+'/'+outer.f;let a=this.fragments.get(key);if(!a){if(this.fragments.size>=8||[...this.fragments.values()].reduce((n,x)=>n+x.size,0)>24*1024*1024)return;a={parts:new Map(),n:outer.n,at:now,size:0};this.fragments.set(key,a);}if(a.n!==outer.n)return;if(!a.parts.has(outer.i)){a.parts.set(outer.i,outer.d);a.size+=outer.d.length;}if(a.size>MAX*1.4){this.fragments.delete(key);return;}if(a.parts.size!==a.n)return;this.fragments.delete(key);payload=dec.decode(un64(Array.from({length:a.n},(_,i)=>a.parts.get(i)).join('')));outer=JSON.parse(payload);}
  if(topic.startsWith(PREFIX+'/lobby/')){if(!outer||outer.content!==R.CONTENT_HASH||typeof outer.invite!=='string'||outer.invite.length>1600||typeof outer.name!=='string'||outer.name.length>40||!Number.isFinite(outer.at)||now-outer.at>45000||outer.at>now+30000)return;parseInvite(outer.invite);if(this.rooms.size<128||this.rooms.has(topic)){this.rooms.set(topic,outer);this.emitRooms();}return;}
  if(this.hosting){const id=topic.split('/').pop();if(!/^[A-Za-z0-9_-]{22}$/.test(id))return;let ch=this.channels.get(id);
   if(topic===this.baseTopic+'/join/'+id){if(!ch){if(this.channels.size>=20||un64(outer.p).length!==65)return;ch={key:await derive(this.pair,outer.p,this.inv,id),publicKey:outer.p,tx:0,rx:0,queue:Promise.resolve(),active:false};}else if(ch.publicKey!==outer.p)return;
    const message=await open(ch,topic,outer.e);if(!['join','watch','resume'].includes(message.type)||message.code!==this.room)return;
    if(ch.active){this.transmit(ch,this.baseTopic+'/down/'+id,{type:'relayResume'});this.toWorker(id,{type:'resync',...R.netIdentity()});return;}ch.active=true;this.channels.set(id,ch);this.toWorker(id,{...message,type:'hello'});this.toWorker(id,message);return;
   }
   if(ch?.active&&topic===this.baseTopic+'/up/'+id){const message=await open(ch,topic,payload);this.toWorker(id,message);}return;
  }
  if(this.channel&&topic===this.baseTopic+'/down/'+this.peerId){const message=await open(this.channel,topic,payload);this.lastHost=now;this.accept(message);}
 }
 emitRooms(){const now=Date.now();for(const [key,r]of this.rooms)if(now-r.at>45000)this.rooms.delete(key);this.receive({type:'rooms',rooms:[...this.rooms.values()].map(r=>({code:r.code,name:r.name,map:r.map,players:r.players,seats:r.seats,invite:r.invite,started:r.started})),mqtt:true},this);}
 advertise(){if(!this.hosting||!this.invite||!this.mqtt?.connected)return;const topic=PREFIX+'/lobby/'+this.inv.r;if(this.payload.private!==false){if(this.advertised){this.publish(topic,'',1,true);this.advertised=false;}return;}if(Date.now()-(this.lastAdvert||0)<15000)return;this.lastAdvert=Date.now();const message={name:String(this.payload.roomName||this.payload.name+' 的房间').slice(0,40),code:this.room,invite:this.invite,map:this.config?.map||'valley',players:this.members?.length||1,seats:this.config?.players||2,started:!!this.started,content:R.CONTENT_HASH,at:Date.now()};this.publish(topic,JSON.stringify(message),1,true);this.advertised=true;}
 accept(m){if(this.intentional)return;if(m.type==='roomClosed'){this.connected=false;this.intentional=true;clearInterval(this.heartbeat);clearInterval(this.handshakeTimer);clearTimeout(this.joinTimer);clearTimeout(this.retryTimer);this.mqtt?.close();this.status(m.message||'房主已退出，房间已结束。','error');this.receive({type:'error',message:m.message||'房主已退出，房间已结束。'},this);return;}if(m.type==='relayResume'){this.connected=true;this.disconnectedAt=null;this.status('加密连接已恢复','connected');this.send({type:'ping',at:Date.now()});return;}
  if(m.type==='welcome'){this.token=m.token;this.room=m.code;this.player=m.player;this.seq=Math.max(this.seq,m.seq||0);this.spectator=!!m.spectator;this.connected=true;this.baseline=null;this.disconnectedAt=null;clearTimeout(this.joinTimer);if(this.hosting){this.inv.c=m.code;this.invite='RA1.'+b64(enc.encode(JSON.stringify(this.inv)));this.advertise();}this.status(this.hosting?'公共中转已连接 · 房主模拟运行中':'加密房间已连接 · '+(m.spectator?'只读观战':'席位 '+(m.player+1)),'connected');}
  if(m.type==='lobby'){this.config=m.config;this.members=m.members;this.host=m.host;this.room=m.code;if(this.hosting)this.advertise();}
  if(m.type==='start'){this.started=true;this.spectator=!!m.spectator;if(this.hosting){this.lastAdvert=0;this.advertise();}}
  if(m.type==='rematch'){this.started=false;this.seq=0;this.lastAdvert=0;this.advertise();}
  if(m.type==='pong'){this.ping=Math.max(0,Date.now()-m.at);if(!this.connected){this.connected=true;this.send({type:'resync'});this.status('房主连接已恢复','connected');}this.receive({type:'latency',ping:this.ping},this);return;}
  if(m.type==='state'&&m.id){this.baseline={id:m.id,data:m.data};this.send({type:'ack',id:m.id});}
  if(m.type==='delta'){try{if(!this.baseline||m.base!==this.baseline.id)throw Error();const data=R.Wire.apply(this.baseline.data,m.data);this.baseline={id:m.id,data};this.send({type:'ack',id:m.id});m={type:'state',data,id:m.id};}catch{this.baseline=null;this.send({type:'resync'});return;}}
  this.receive(m,this);
 }
 send(message){if(this.intentional||this._closing||!this.connected||!this.mqtt?.connected)return false;const m={...R.netIdentity(),...message};if(this.hosting){this.toWorker('self',m);return true;}if(!this.channel){if(m.type==='list'){this.emitRooms();return true;}return false;}return this.transmit(this.channel,this.baseTopic+'/up/'+this.peerId,m);}
 command(command){if(!this.connected||this.spectator||!this.mqtt?.connected)return false;const seq=this.seq+1;if(this.send({type:'command',seq,command})){this.seq=seq;return true;}return false;}
 close(){if(this.intentional||this._closing)return;
  // Final notification is best effort; a power loss cannot send one. The heartbeat still detects it.
  if(this.hosting&&this.mqtt?.connected){for(const [id,ch]of this.channels)if(ch.active)this.transmit(ch,this.baseTopic+'/down/'+id,{type:'roomClosed',message:'房主已退出，房间已结束。请重新创建或加入房间。'});if(this.advertised)this.publish(PREFIX+'/lobby/'+this.inv.r,'',1,true);}
  else if(!this.hosting&&this.channel&&this.connected)this.send({type:'leave'});
  this._closing=true;this.connected=false;clearInterval(this.heartbeat);clearInterval(this.handshakeTimer);clearTimeout(this.joinTimer);clearTimeout(this.retryTimer);
  const queues=this.hosting?[...this.channels.values()].map(c=>c.queue):[this.channel?.queue];
  this.closePromise=Promise.race([Promise.allSettled(queues.filter(Boolean)),new Promise(r=>setTimeout(r,600))]).finally(()=>{this.intentional=true;this.mqtt?.close();this.worker?.terminate();this.channels.clear();this.fragments.clear();});return this.closePromise;
 }
};
})(globalThis);
