/* Local-first release UI. No telemetry, remote assets or automatic broker connection. */
(function(G){'use strict';const R=G.RA,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=t=>Math.floor(t/60)+':'+Math.floor(t%60).toString().padStart(2,'0');
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d;}catch{return d;}},store=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}};
R.SaveVault={
 async db(){return new Promise((resolve,reject)=>{if(!G.indexedDB)return reject(Error('当前浏览器禁止本地数据库，请导出存档文件'));const r=indexedDB.open('ra3d-command-vault',1);r.onupgradeneeded=()=>r.result.createObjectStore('saves',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('本地存档数据库不可用'));});},
 async write(id,data,label){R.Sim.load(data);if(JSON.stringify(data).length>12*1024*1024)throw Error('单份存档超过12MB');const db=await this.db();return new Promise((resolve,reject)=>{const tx=db.transaction('saves','readwrite');tx.objectStore('saves').put({id,label,data,at:Date.now(),map:data.cfg.map,tick:data.tick,operation:data.operation?.name||''});tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(Error('空间不足或浏览器禁止写入；请导出文件'));};});},
 async list(){const db=await this.db();return new Promise((resolve,reject)=>{const tx=db.transaction('saves'),r=tx.objectStore('saves').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('读取存档失败'));tx.oncomplete=()=>db.close();});},
 async remove(id){const db=await this.db();return new Promise((resolve,reject)=>{const tx=db.transaction('saves','readwrite');tx.objectStore('saves').delete(id);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(Error('删除失败'));};});}
};
function modal(id,title,content){const el=document.createElement('div');el.id=id;el.className='modal hidden';el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.innerHTML=`<section class="modal-panel wide-panel"><div class="panel-head"><div><div class="hq-kicker">COMMAND / 1.0</div><h2>${esc(title)}</h2></div><button data-dismiss class="ghost">关闭 ×</button></div>${content}</section>`;document.body.append(el);el.querySelector('[data-dismiss]').onclick=()=>el.classList.add('hidden');return el;}
R.initRelease=function(){const app=R.app;app.networkTransport='mqtt';app.matchSeed=260912;app.operationId=null;
 // A dedicated cooperative operations page, without losing the existing tutorial page.
 const nav=document.createElement('button');nav.dataset.page='operations';nav.innerHTML='<small>03</small><span>合作行动</span>';$('hq-nav').insertBefore(nav,$('hq-nav').children[2]);[...$('hq-nav').children].forEach((b,i)=>b.querySelector('small').textContent=String(i+1).padStart(2,'0'));
 const opPage=document.createElement('section');opPage.id='page-operations';opPage.className='hq-page hidden';opPage.innerHTML=`<div class="page-intro"><div class="hq-kicker">COOPERATIVE OPERATIONS / SIX FRONTS</div><h3>不同的目标，同一支队伍。</h3><p>单人模式由友军电脑协同；联机支持两名指挥官。先选择行动，再由房主开设加密房间。</p></div><div id="operation-cards"></div><div class="release-note"><b>任务规则</b><span>任务不靠普通歼灭判定取胜。星级按完成目标、标准时间与团队损失统计，存档与录像会保留进度。</span></div>`;$('hq-main').append(opPage);
 function operationCards(){const records=read('ra3d-operations',{});$('operation-cards').innerHTML=R.OPERATIONS.map((o,i)=>`<article class="operation-card" data-op-card="${o.id}"><div class="operation-art op-${o.id}"><span>OP / 0${i+1}</span><b>${['Ⅷ','◆','↗','⌁','Ψ','⌂'][i]}</b><small>${esc(R.getMap(o.map).en)}</small></div><div class="operation-copy"><small>${esc(o.tag)} <span>${'★'.repeat(records[o.id]?.stars||0)}${'☆'.repeat(3-(records[o.id]?.stars||0))}</span></small><h3>${esc(o.name)}</h3><p>${esc(o.description)}</p><div class="op-meta">${esc(R.getMap(o.map).name)} · 时限 ${Math.round(o.limit/60)} 分钟</div><div class="op-actions"><button data-operation="${o.id}" class="primary">单人行动</button><button data-coop="${o.id}">与朋友合作</button></div></div></article>`).join('');for(const b of document.querySelectorAll('[data-operation]'))b.onclick=()=>{app.operationId=null;app.startLocal(R.operationConfig(b.dataset.operation,{nation:$('nation').value,difficulty:$('difficulty').value,seed:app.matchSeed}));};for(const b of document.querySelectorAll('[data-coop]'))b.onclick=()=>setOperation(b.dataset.coop);}
 function setOperation(id){if(app.net?.room){app.toast('请先离开当前房间再选择行动',true);return;}const c=R.operationConfig(id,{nation:$('nation').value,seed:app.matchSeed});app.operationId=id;app.setupSlots=c.slots;for(const k of ['map','players','teams','credits'])$(k).value=String(c[k]);app.showPage('network');$('operation-select').value=id;$('operation-select').dispatchEvent(new Event('change'));app.toast('合作任务已选择。创建房间后，把邀请口令发给朋友。');}
 const setup=document.createElement('details');setup.id='advanced-setup';setup.open=true;setup.innerHTML='<summary>国家、地图与规则设置</summary>';$('setup-fields').before(setup);setup.append($('setup-fields'));setup.append($('nation-info'));const panel=setup.parentElement;panel.insertBefore($('network-ui'),setup);$('credits').add(new Option('$18,000（行动预设）','18000'));
 const oldPage=app.showPage;app.showPage=page=>{if(page==='operations'){if(app.playing)return;for(const e of document.querySelectorAll('.hq-page'))e.classList.add('hidden');opPage.classList.remove('hidden');$('page-title').textContent='合作行动';app.page=page;for(const b of $('hq-nav').children)b.classList.toggle('active',b.dataset.page===page);operationCards();return;}oldPage(page);setup.open=page!=='network';setup.classList.toggle('setup-collapsible',page==='network');if(page==='network')updateTransport();if(page==='replays')renderVault();};nav.onclick=()=>app.showPage('operations');
 for(const b of $('hq-nav').children)b.onclick=()=>app.showPage(b.dataset.page);
 for(const b of document.querySelectorAll('[data-go]'))b.onclick=()=>app.showPage(b.dataset.go);$('home-play').onclick=()=>app.showPage('skirmish');$('home-train').onclick=()=>app.showPage('training');
 const homeOps=document.createElement('button');homeOps.id='home-operations';homeOps.textContent='六个合作行动';$('home-train').after(homeOps);homeOps.onclick=()=>app.showPage('operations');
 $('page-home').querySelector('.hq-kicker').textContent='COMMAND EDITION 1.0 / DEPLOY TOGETHER';$('page-home').querySelector('.home-bottom article p').textContent='六个合作任务、五个教学目标与守卫挑战。';
 const ribbon=document.createElement('div');ribbon.className='release-ribbon';ribbon.innerHTML='<span>1.0</span><div><b>公共中转联机已接入</b><small>无需自建服务器 · 邀请口令 · 房主浏览器模拟</small></div><button id="home-online">在线建房 ↗</button>';$('page-home').prepend(ribbon);$('home-online').onclick=()=>{app.showPage('network');$('transport-select').value='mqtt';updateTransport();};
 const network=$('network-ui');network.insertAdjacentHTML('afterbegin',`<div class="transport-picker"><label>连接方式<select id="transport-select"><option value="mqtt">公共 MQTT 中转 · 不用自建服务器</option><option value="lan">局域网 / 专用服务器 · 直接连接</option></select></label><div id="broker-controls"><label>公共节点<input id="broker-url" list="broker-options" spellcheck="false" value="${R.DEFAULT_BROKER}"></label><datalist id="broker-options">${R.BROKER_ALTERNATIVES.map(url=>`<option value="${url}">`).join('')}</datalist><p class="micro-note">默认 EMQX，创建失败可尝试候选节点。公共测试服务不保证稳定性或中国大陆可达性；备选地址不代表已核验可用。推荐2–4人，房主须保持页面开启。</p></div><label>合作行动<select id="operation-select"><option value="">标准遭遇战</option>${R.OPERATIONS.map(o=>`<option value="${o.id}">${esc(o.name)} · 2人协作</option>`).join('')}</select></label></div>`);
 $('room-code').maxLength=1800;$('private-room').checked=true;$('private-room').parentElement.lastChild.textContent=' 私密房间，不在公开目录发布邀请口令';
 const serverField=$('server-url').closest('.field')||$('server-url').parentElement;
 function updateTransport(){if(app.net?.room&&app.net.transport!=='mqtt'&&$('transport-select').value==='mqtt'||app.net?.room&&app.net.transport==='mqtt'&&$('transport-select').value!=='mqtt'){app.toast('请先离开房间，再切换连接方式',true);$('transport-select').value=app.net.transport==='mqtt'?'mqtt':'lan';}
  const mqtt=$('transport-select').value==='mqtt';setup.open=app.page!=='network';setup.classList.toggle('setup-collapsible',app.page==='network');app.networkTransport=mqtt?'mqtt':'lan';$('broker-controls').classList.toggle('hidden',!mqtt);serverField.classList.toggle('hidden',mqtt);$('room-code').placeholder=mqtt?'粘贴完整 RA1. 邀请口令':'6位房间码';$('copy-invite').textContent=mqtt?'复制加密邀请口令':'复制局域网邀请链接';$('online-gate').innerHTML=mqtt?'<b>公共中转 / 浏览器房主</b><p>双方打开同一完整包。房主创建房间后发送邀请口令；朋友无需运行服务器。房主关闭页面会结束房间，掉线时暂时停止下令。</p>':'<b>局域网 / 专用服务器</b><p>房主运行 START_LAN.bat，同网络的朋友打开邀请链接。此方式由 Node 服务模拟，不依赖公共 MQTT 节点。</p>';
  if(mqtt){const go=document.createElement('button');go.id='online-entry';go.textContent='连接并查看公开房间';go.onclick=()=>app.connect('list');$('online-gate').append(go);}
  $('mode-description').textContent=mqtt?'邀请口令包含房间密钥与绑定节点，请只发给参战者。取消“私密房间”会把邀请发布到当前节点目录。':'房主调整席位和地图，所有玩家准备后开始。两分钟内可恢复原席位。';
 }
 $('transport-select').onchange=updateTransport;
 $('operation-select').onchange=()=>{if(app.net?.room)return app.toast('合作行动请在创建房间前选择',true);const id=$('operation-select').value;app.operationId=id||null;if(id){const c=R.operationConfig(id,{nation:$('nation').value,seed:app.matchSeed});app.setupSlots=c.slots;for(const k of ['map','players','teams','credits'])$(k).value=String(c[k]);}else app.setupSlots=R.defaultSlots(+$('players').value,$('nation').value,$('teams').value);oldPage('network');updateTransport();for(const id of ['players','teams','map'])$(id).disabled=!!app.operationId;};
 const quickJoin=document.createElement('div');quickJoin.className='quick-join-block';const oldControls=$('host-room').parentElement;quickJoin.append(oldControls);quickJoin.append($('net-status'));quickJoin.append($('lobby'));$('transport-select').parentElement.after(quickJoin);
 const invite=document.createElement('textarea');invite.id='invite-output';invite.readOnly=true;invite.rows=3;invite.className='hidden';invite.setAttribute('aria-label','加密房间邀请口令');$('diagnostic-output').after(invite);
 const oldCopy=$('copy-invite').onclick;$('copy-invite').onclick=async()=>{if(app.networkTransport!=='mqtt')return oldCopy();if(!app.net?.invite)return app.toast('先创建或加入加密房间',true);invite.value=app.net.invite;invite.classList.remove('hidden');invite.select();try{await navigator.clipboard.writeText(app.net.invite);app.toast('邀请口令已复制。朋友在同版本完整包中粘贴加入。');}catch{app.toast('口令已选中，可按 Ctrl+C 复制。');}};
 const watch=document.createElement('button');watch.id='watch-room';watch.className='ghost';watch.textContent='延迟观战';$('join-room').after(watch);watch.onclick=()=>app.connect('watch');
 const oldCheck=$('network-check').onclick;$('network-check').onclick=async()=>{if(app.networkTransport!=='mqtt')return oldCheck();const out=$('diagnostic-output');out.textContent='检查加密功能和节点协议握手…';let wire;try{await R.RelayCrypto.keypair();const url=$('broker-url').value,at=performance.now();wire=new R.MQTTWire(url,{timeout:7000});await wire.connect();await wire.subscribe('ra3d-command/100/probe/'+R.RelayCrypto.b64(crypto.getRandomValues(new Uint8Array(12))));out.textContent=`MQTT握手与订阅成功，耗时 ${Math.round(performance.now()-at)} ms。节点：${new URL(url).hostname}。这不是跨运营商对局质量保证。`; }catch(e){out.textContent='诊断未通过：'+e.message+'。更换候选节点；确认浏览器允许网络连接。';}finally{wire?.close();}};
 const info=document.createElement('button');info.textContent='联机原理与隐私';info.id='privacy-info';$('network-check').after(info);modal('privacy-modal','联机与隐私说明',`<div class="release-readme"><h3>公共节点只中转消息</h3><p>本机房主的独立工作线程执行与局域网服务器相同的模拟。消息经过 MQTT / WSS 中转，游戏不要求账号、端口映射或自行部署服务器。</p><h3>哪些信息会离开电脑</h3><p>节点可以看到连接IP、主题和流量；房间游戏消息使用独立 ECDH + AES-GCM 通道。私密房间不发布邀请。公开房间会主动公开昵称、地图、人数和加入口令。不要在公开房间输入敏感信息。</p><h3>安全边界</h3><p>邀请口令持有者可以加入。房主掌握完整战场，能够修改本机程序，因此不适用于排位、奖金比赛或不信任房主的场景。恶意节点仍可丢弃消息或拒绝服务。消息加密不等于已经通过第三方安全审计。</p><h3>掉线与观战</h3><p>短暂网络中断会自动重连。房主必须保持页面开启；没有跨房主无缝迁移。观战延迟30秒，切到尚未缓存的视角需重新等待。观战者不能下令或向参战玩家聊天。</p></div>`);info.onclick=()=>$('privacy-modal').classList.remove('hidden');
 const oldNetwork=app.onNetwork;app.onNetwork=(m,net)=>{
  if(m.type==='rooms'){$('room-directory').innerHTML=m.rooms.length?m.rooms.map((r,i)=>`<div class="room-directory-entry"><span><b>${esc(r.name)}</b><small>${esc(R.getMap(r.map).name)} · ${r.players}/${r.seats}人 · ${r.started?'进行中':'准备中'}</small></span><div>${!r.started?`<button data-directory-index="${i}">加入</button>`:''}<button data-spectate-index="${i}">观战</button></div></div>`).join(''):'<p class="empty-state">当前节点没有公开房间。私密房间请使用邀请口令加入。</p>';for(const b of document.querySelectorAll('[data-directory-index],[data-spectate-index]'))b.onclick=()=>{const watching=b.dataset.spectateIndex!==undefined,r=m.rooms[+(b.dataset.directoryIndex??b.dataset.spectateIndex)];$('room-code').value=r.invite||r.code;app.connect(watching?'watch':'join');};return;}
  if(m.type==='spectatorWait'){$('connection-banner').classList.remove('hidden');$('connection-banner').textContent=`延迟观战缓冲中：约 ${m.seconds} 秒。观战不会获得实时敌方状态。`;return;}
  oldNetwork?.(m,net);
 };
 const oldLobby=app.onLobby;app.onLobby=m=>{oldLobby?.(m);app.operationId=m.config.operation||null;$('operation-select').value=app.operationId||'';$('operation-select').disabled=true;if(app.net?.transport==='mqtt'&&app.net.invite){$('broker-url').value=app.net.url;$('broker-url').disabled=true;invite.value=app.net.invite;invite.classList.remove('hidden');}if(m.spectator){$('net-status').textContent='只读观战席 · 30秒延迟';$('ready-room').disabled=true;}};
 const disconnect=app.disconnect;app.disconnect=()=>{disconnect();$('operation-select').disabled=false;$('broker-url').disabled=false;};$('leave-room').onclick=()=>app.disconnect();
 // Dedicated observer controls. No UI path can send game commands while observing.
 $('hud').insertAdjacentHTML('beforeend','<div id="observer-bar" class="hidden"><b>只读观战 / 30s</b><select id="observer-view" aria-label="观战视角"></select><span id="observer-latency"></span><button id="observer-leave">退出观战</button></div>');$('observer-leave').onclick=()=>app.quit();$('observer-view').onchange=()=>{app.selected.clear();app.net?.send({type:'spectateView',player:+$('observer-view').value});};
 // IndexedDB provides separate rolling autosaves and four explicit manual slots.
 $('page-replays').insertAdjacentHTML('beforeend','<div class="section-label">指挥存档 <button id="vault-refresh">刷新存档</button></div><div id="vault-list"></div><p class="micro-note">本机保存4个手动槽位和2个交替自动槽位。单人对局每60秒自动保存；浏览器隐私模式、配额或清理数据可能删除存档，请导出重要进度。</p>');
 modal('vault-modal','现场存档','<p>手动存档仅用于单人对局。选择一个槽位会覆盖该槽位；重要存档可另存为JSON文件。</p><div id="vault-live"></div><div id="vault-feedback" role="status"></div>');
 app.captureSave=()=>new Promise((resolve,reject)=>{if(!app.worker||app.net||app.replayMode)return reject(Error('请在单人对局中保存'));const id=++app.request,timer=setTimeout(()=>{app.pending.delete(id);reject(Error('存档响应超时'));},9000);app.pending.set(id,data=>{clearTimeout(timer);resolve(data);});app.worker.postMessage({type:'save',request:id});});
 const saveButton=document.createElement('button');saveButton.id='hud-save-vault';saveButton.textContent='存档';$('hud-utilities').append(saveButton);saveButton.onclick=async()=>{if(app.net||app.replayMode)return app.toast('联机和录像模式不可保存单人槽位',true);$('vault-modal').classList.remove('hidden');$('vault-live').innerHTML=Array.from({length:4},(_,i)=>`<button data-save-slot="manual${i+1}">保存到槽位 ${i+1}</button>`).join('')+'<button id="vault-export">导出文件</button>';for(const b of document.querySelectorAll('[data-save-slot]'))b.onclick=async()=>{try{await R.SaveVault.write(b.dataset.saveSlot,await app.captureSave(),'手动槽位 '+b.dataset.saveSlot.slice(-1));$('vault-feedback').textContent='存档已写入本机数据库。';}catch(e){$('vault-feedback').textContent=e.message;}};$('vault-export').onclick=async()=>{try{app.download('RA3D_1.0.0.save.json',JSON.stringify(await app.captureSave()),'application/json');}catch(e){app.toast(e.message,true);}};};
 let autoIndex=0,autoBusy=false;app.onAutosave=async data=>{if(autoBusy||app.net||app.replayMode)return;autoBusy=true;try{await R.SaveVault.write('auto'+(autoIndex%2),data,'自动存档 '+(++autoIndex));app.lastAutosave=Date.now();}catch(e){if(!app.autoWarned){app.autoWarned=true;app.toast('自动存档未写入：'+e.message,true);}}finally{autoBusy=false;}};
 async function renderVault(){try{const list=await R.SaveVault.list();$('vault-list').innerHTML=list.length?list.sort((a,b)=>b.at-a.at).map((r,i)=>`<div class="vault-row"><div><b>${esc(r.label)}</b><small>${esc(r.operation||R.getMap(r.map).name)} · ${fmt(r.tick/10)} · ${new Date(r.at).toLocaleString()}</small></div><button data-load-vault="${i}">继续</button><button data-export-vault="${i}">导出</button><button data-delete-vault="${i}" class="ghost">删除</button></div>`).join(''):'<p class="empty-state">暂无存档。单人对局中点击“存档”，或游玩一分钟创建自动存档。</p>';for(const b of document.querySelectorAll('[data-load-vault]'))b.onclick=()=>{try{const data=list[+b.dataset.loadVault].data;R.Sim.load(data);app.startLocal(data.cfg);app.loadSave(data);}catch(e){app.toast(e.message,true);}};for(const b of document.querySelectorAll('[data-export-vault]'))b.onclick=()=>app.download('RA3D_'+list[+b.dataset.exportVault].id+'.json',JSON.stringify(list[+b.dataset.exportVault].data),'application/json');for(const b of document.querySelectorAll('[data-delete-vault]'))b.onclick=async()=>{await R.SaveVault.remove(list[+b.dataset.deleteVault].id);renderVault();};}catch(e){$('vault-list').textContent=e.message;}}
 $('vault-refresh').onclick=renderVault;
 // Technology view is generated from actual build requirements, never a second hardcoded tree.
 modal('tech-modal','科技路线与兵种搭配','<div class="tech-toolbar"><label>国家 <select id="tech-nation">'+R.NATIONS.map(n=>`<option value="${n.id}">${esc(n.name)}</option>`).join('')+'</select></label><span>选择节点查看数值与前置</span></div><div id="tech-detail"></div><div id="tech-tree"></div>');
 const techButton=document.createElement('button');techButton.id='open-tech-tree';techButton.textContent='查看科技路线';$('home-db').after(techButton);const hudTech=document.createElement('button');hudTech.id='hud-tech-tree';hudTech.textContent='科技';$('hud-utilities').append(hudTech);
 const roles={hq:'建造场',power:'发电设施',barracks:'兵营',refinery:'矿场',factory:'战车工厂',radar:'雷达/机场',airfield:'机场',tech:'作战实验室',naval:'造船厂',robotcontrol:'机器人控制中心'};
 function renderTech(){const nation=R.nation($('tech-nation').value),defs=R.defs().filter(d=>d.faction===nation.faction&&!d.sandboxOnly&&(!d.nation||d.nation===nation.id)),tiers=[['基础部署',d=>!d.requires.includes('radar')&&!d.requires.includes('tech')&&!d.requires.includes('factory')],['机械化作战',d=>d.requires.includes('factory')&&!d.requires.includes('radar')&&!d.requires.includes('tech')],['战场支援',d=>d.requires.includes('radar')&&!d.requires.includes('tech')],['尖端科技',d=>d.requires.includes('tech')]];$('tech-tree').innerHTML=tiers.map(([title,test],i)=>`<section class="tech-column"><div class="hq-kicker">TIER / ${i+1}</div><h3>${title}</h3>${defs.filter(test).map(d=>`<button data-tech-unit="${d.id}">${app.icon(d)}<span><b>${esc(d.name)}</b><small>$${d.cost} · ${(d.requires||[]).map(k=>roles[k]||k).join(' + ')||'起始设施'}</small></span></button>`).join('')}</section>`).join('');for(const b of document.querySelectorAll('[data-tech-unit]'))b.onclick=()=>{const d=R.D[b.dataset.techUnit];$('tech-detail').innerHTML=`${app.icon(d)}<div><b>${esc(d.name)} / ${esc(d.id)}</b><p>费用 $${d.cost} · 生命 ${d.hp} · 射程 ${d.range||0} · 速度 ${d.speed||0}</p><small>${esc(d.description||'按前置设施解锁。数据以当前工程实际模拟规则为准。')}</small></div>`;};$('tech-tree').querySelector('[data-tech-unit]')?.click();}
 $('tech-nation').onchange=renderTech;techButton.onclick=hudTech.onclick=()=>{$('tech-nation').value=app.state?.p.nation||$('nation').value;renderTech();$('tech-modal').classList.remove('hidden');};
 app.drawMissionMinimap=()=>{const o=app.state?.operation;if(!o||o.completed||o.failed)return;const canvas=$('minimap'),c=canvas.getContext('2d');c.save();c.strokeStyle='#ffe0a2';c.fillStyle='#ffe0a2';c.lineWidth=1.5;c.font='bold 9px sans-serif';const points=[...(o.points||[])];if(o.id==='escort'&&o.route?.[o.waypoint])points.push(o.route[o.waypoint]);if(o.extraction)points.push(o.extraction);for(const [i,p]of points.entries()){if(o.rescued?.includes(p.id))continue;const x=p.x/192*canvas.width,z=p.z/192*canvas.height;c.strokeRect(x-5,z-5,10,10);c.fillText(String(i+1),x+7,z+3);}c.restore();};
 // Comfort, sound routing and local operation records.
 $('page-settings').insertAdjacentHTML('beforeend',`<div class="profile-card release-settings"><label>高对比文字 <input id="high-contrast" type="checkbox"></label><label>界面提示音 <input id="ui-sound" type="checkbox" checked></label><label>战场音效 <input id="battle-sound" type="checkbox" checked></label><label>随机种子 <input id="match-seed" type="number" min="1" max="4294967295" value="260912"></label><button id="random-seed">生成新种子</button></div><div class="section-label">本机行动记录</div><div id="service-record"></div>`);
 const prefs=read('ra3d-release-prefs',{contrast:false,uiSound:true,battleSound:true});$('high-contrast').checked=prefs.contrast;$('ui-sound').checked=prefs.uiSound;$('battle-sound').checked=prefs.battleSound;document.body.classList.toggle('high-contrast',prefs.contrast);
 for(const id of ['high-contrast','ui-sound','battle-sound'])$(id).onchange=()=>{prefs.contrast=$('high-contrast').checked;prefs.uiSound=$('ui-sound').checked;prefs.battleSound=$('battle-sound').checked;document.body.classList.toggle('high-contrast',prefs.contrast);store('ra3d-release-prefs',prefs);};const playSound=app.sound.play.bind(app.sound);app.sound.play=kind=>{if(['shot','explosion'].includes(kind)?prefs.battleSound:prefs.uiSound)playSound(kind);};
 $('match-seed').onchange=()=>{app.matchSeed=(Number($('match-seed').value)||260912)>>>0;};$('random-seed').onclick=()=>{$('match-seed').value=String(crypto.getRandomValues(new Uint32Array(1))[0]||1);$('match-seed').onchange();};
 function records(){const a=read('ra3d-operations',{});$('service-record').innerHTML=R.OPERATIONS.map(o=>`<div><b>${esc(o.name)}</b><span>${'★'.repeat(a[o.id]?.stars||0)}${'☆'.repeat(3-(a[o.id]?.stars||0))}</span><small>${a[o.id]?.best?fmt(a[o.id].best):'尚未完成'}</small></div>`).join('');}
 const result=app.afterResult;app.afterResult=s=>{result?.(s);if(s.operation){$('result-title').textContent=s.operation.completed?'行动成功':'行动中止';$('result-description').textContent=s.operation.reason||s.operation.objective;if(!app.replayMode&&!app.net?.spectator&&s.operation.completed){const data=read('ra3d-operations',{}),old=data[s.operation.id];data[s.operation.id]={stars:Math.max(old?.stars||0,s.operation.stars),best:Math.min(old?.best||Infinity,s.time),at:Date.now()};store('ra3d-operations',data);records();}$('result-description').textContent+=' '+('★'.repeat(s.operation.stars||0));}if(app.net?.spectator){$('result-rematch').disabled=true;$('result-swap').disabled=true;}};
 const upgrade=app.upgradeUI;let observerKey='';app.upgradeUI=s=>{upgrade?.(s);$('hud-save-vault').disabled=!!app.net||!!app.replayMode;$('observer-bar').classList.toggle('hidden',!app.net?.spectator);if(app.net?.spectator){$('connection-banner').classList.add('hidden');$('observer-latency').textContent=(s.delay||0)+'秒延迟 · '+(app.net.ping??'?')+'ms';const key=s.players.map(p=>p.id+':'+p.name).join('|');if(key!==observerKey){observerKey=key;$('observer-view').innerHTML=s.players.filter(p=>!p.closed).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');}$('observer-view').value=String(s.player);$('hud-chat').disabled=true;$('hud-marker').disabled=true;}
  if(s.operation&&!s.replay&&!app.net?.spectator){const o=s.operation;$('mission-panel').classList.remove('hidden');$('mission-kicker').textContent='COOPERATIVE OPERATION';$('mission-title').textContent=o.name;$('mission-text').textContent=o.objective;$('mission-progress').textContent=`${o.progress} / ${o.total} · 剩余 ${fmt(o.remaining)}`+(o.id==='escort'?` · 护卫${o.escortPresent?'就位':'未就位'} · 补给车 ${Math.round((o.convoyHealth??1)*100)}%`:o.id==='extraction'&&o.progress>=3?` · 撤离区 ${o.hold}/30秒`:o.id==='oil'?` · 控制 ${o.controlled||0}/3座`:o.id==='holdout'?` · 下一波约 ${o.wave>=8?0:o.nextWaveIn}秒`: '');$('mission-next').classList.add('hidden');$('mission-back').textContent='退出行动';}
 };
 // Show objective locations on the minimap and in the world without revealing enemy entities.
 
 $('about-modal').querySelector('section').innerHTML=`<div class="panel-head"><h2>Command Edition 1.0.0</h2><button id="close-release-about">关闭 ×</button></div><div class="release-readme"><h3>本版内容</h3><p>公共 MQTT 中转、同规则浏览器房主、私密邀请、节点选择与诊断；六个合作任务、30秒延迟观战、检查点录像、多槽存档与自动保存、科技路线、行动记录及扩展模型细节。</p><h3>交付边界</h3><p>这是本项目的1.0版本，不是原版《尤里的复仇》全部数值、关卡、语音、美术和行为的完整复刻。高级机制仍有工程化近似实现。</p><p>公共节点由第三方运营，没有可用性或中国大陆连接质量保证。房主离开会结束房间。没有排位系统、账号云存档、可信反作弊或无缝主机迁移。</p><p>本地资产独立打包，无CDN、无自动连接、无统计上报。只有点击连接相关按钮后才访问选择的节点。</p><p class="micro-note">版本 ${R.VERSION} · protocol ${R.PROTOCOL}<br>规则 ${R.RULES_HASH} · 内容 ${R.CONTENT_HASH}</p></div>`;$('close-release-about').onclick=()=>$('about-modal').classList.add('hidden');
 const returnHome=app.returnHome;app.returnHome=()=>{returnHome?.();$('broker-url').disabled=false;$('observer-bar').classList.add('hidden');$('operation-select').disabled=false;app.operationId=null;$('operation-select').value='';for(const k of ['players','teams','map'])$(k).disabled=false;};
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&app.net?.hosting)app.net.status('房主页面进入后台，浏览器可能限制计时。请保持此窗口可见。','reconnecting');else if(!document.hidden&&app.net?.hosting&&app.net.connected)app.net.status('房主页面已恢复前台','connected');});
 const qp=location.hash.startsWith('#ra=')?location.hash.slice(4):null;if(qp){try{R.RelayCrypto.parseInvite(qp);$('room-code').value=qp;app.showPage('network');app.toast('加密邀请已就绪，点击加入。');}catch(e){app.toast(e.message,true);}}
 // Focus trapping for keyboard users, independent of gameplay shortcut handling.
 document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const visible=[...document.querySelectorAll('.modal:not(.hidden)')].pop();if(!visible)return;const nodes=[...visible.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(n=>!n.disabled&&n.offsetParent);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||!visible.contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!visible.contains(document.activeElement))){e.preventDefault();first.focus();}},true);
 const missionBack=$('mission-back').onclick;$('mission-back').onclick=()=>{if(app.state?.operation){app.quit();app.showPage('operations');}else missionBack?.();};
 window.addEventListener('beforeunload',e=>{if(app.net?.hosting&&app.net?.room){e.preventDefault();e.returnValue='';}});
 operationCards();records();updateTransport();
};
})(globalThis);
