'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{Worker:Thread}=require('node:worker_threads');
const {TestBroker}=require('./fixtures/mqtt-broker.cjs'),ROOT=path.resolve(__dirname,'..');
require('../web/src/data.js');require('../web/src/sim.js');require('../web/src/wire.js');require('../web/src/net.js');require('../web/src/mqtt-wire.js');require('../web/src/mqtt-room.js');
const R=globalThis.RA;globalThis.location=new URL('http://localhost');
// Browser-host Worker adapter uses the actual shipped source, not a second simulation.
const sources={'data-source':'data.js','sim-source':['sim.js','tactics.js','operations.js'],'wire-source':'wire.js','authority-source':'authority.js'};
globalThis.document={getElementById:id=>({textContent:[sources[id]].flat().map(f=>fs.readFileSync(path.join(ROOT,'web/src',f),'utf8')).join('\n')})};
globalThis.Worker=class{
 constructor(url){this.queue=[];this.dead=false;fetch(url).then(r=>r.text()).then(source=>{if(this.dead)return;this.worker=new Thread(`const {parentPort}=require('node:worker_threads');globalThis.postMessage=m=>parentPort.postMessage(m);parentPort.on('message',m=>globalThis.onmessage?.({data:m}));(function(){const module=undefined;${source}\n})();`,{eval:true});this.worker.on('message',data=>this.onmessage?.({data}));this.worker.on('error',e=>this.onerror?.(e));for(const m of this.queue)this.worker.postMessage(m);this.queue=[];}).catch(e=>this.onerror?.(e));}
 postMessage(m){if(this.worker)this.worker.postMessage(m);else this.queue.push(m);}terminate(){this.dead=true;this.worker?.terminate();}
};
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label,timeout=8000){const end=Date.now()+timeout;while(Date.now()<end){if(fn())return;await wait(25);}throw Error('Timeout: '+label);}
let checks=[],failures=[],clients=[];async function test(name,fn){try{await fn();checks.push(name);console.log('PASS',name);}catch(e){failures.push({name,error:e.stack});console.error('FAIL',name,e.message);throw e;}}
function client(url,action,payload){const log=[],status=[];let c=new R.MqttRoomClient(url,action,payload,(m)=>log.push(m),(text,kind)=>status.push({text,kind}));c.log=log;c.statusLog=status;clients.push(c);return c;}
function last(c,type){return c.log.filter(m=>m.type===type).at(-1);}
(async()=>{const broker=new TestBroker(18885);await broker.ready;const url='ws://127.0.0.1:18885/mqtt';let host,guest,watcher;
try{
 await test('MQTT 3.1.1 native WebSocket CONNECT / SUBSCRIBE / QoS1',async()=>{let seen;const a=new R.MQTTWire(url,{message:(t,b)=>seen=new TextDecoder().decode(b)}),b=new R.MQTTWire(url);await a.connect();await a.subscribe('fixture/qos');await b.connect();assert.equal(b.publish('fixture/qos','hello',1),true);await until(()=>seen==='hello','QoS1 roundtrip');await until(()=>b.pending.size===0,'PUBACK');a.close();b.close();});
 await test('Bounded parser accepts fragmentation and rejects oversized length',()=>{let received=[];const p=new R.MQTTCodec.Parser((h,b)=>received.push([h,b.length]));const packet=R.MQTTCodec.packet(0x30,new Uint8Array(173));for(let i=0;i<packet.length;i+=7)p.push(packet.subarray(i,i+7));assert.deepEqual(received,[[48,173]]);assert.throws(()=>new R.MQTTCodec.Parser(()=>{},10).push(new Uint8Array([0x30,11])),/过大/);assert.throws(()=>p.push(new Uint8Array([0x30,255,255,255,255])),/无效/);});
 await test('ECDH pairwise keys roundtrip, reject wrong AAD and replay',async()=>{const a=await R.RelayCrypto.keypair(),b=await R.RelayCrypto.keypair(),C=R.RelayCrypto,iv={r:'room',k:C.b64(crypto.getRandomValues(new Uint8Array(32)))};const pub=async k=>C.b64(new Uint8Array(await crypto.subtle.exportKey('raw',k.publicKey)));const ca={key:await C.derive(a,await pub(b),iv,'id'),tx:0,rx:0},cb={key:await C.derive(b,await pub(a),iv,'id'),tx:0,rx:0};const text=await C.seal(ca,'channel',{type:'test',value:'秘密'});await assert.rejects(()=>C.open(cb,'wrong-channel',text));assert.equal((await C.open(cb,'channel',text)).value,'秘密');await assert.rejects(()=>C.open(cb,'channel',text),/重复/);});
 await test('Browser host starts shared RoomService through MQTT',async()=>{host=client(url,'create',{name:'Host100',nation:'usa',private:true,config:{players:2,map:'valley',fogMode:'double',slots:R.defaultSlots(2,'usa')}});await until(()=>host.invite&&last(host,'lobby'),'host room');assert.match(host.invite,/^RA1\./);assert.equal(host.connected,true);assert.ok(![...broker.retained.keys()].some(k=>k.includes('/lobby/')));});
 await test('Guest joins encrypted invitation without local game server',async()=>{guest=client(url,'join',{name:'Guest100',nation:'russia',code:host.invite});await until(()=>guest.token&&last(host,'lobby')?.members.length===2,'encrypted join');assert.equal(guest.player,1);assert.equal(guest.room,host.room);});
 await test('Invitations pin broker and host key; malformed invitations rejected',()=>{const inv=R.RelayCrypto.parseInvite(host.invite);assert.equal(inv.b,url);assert.equal(R.RelayCrypto.un64(inv.h).length,65);assert.throws(()=>R.RelayCrypto.parseInvite('RA1.broken'));assert.throws(()=>R.RelayCrypto.parseInvite(host.invite.toUpperCase()));});
 await test('Room ready / start sends distinct fog-filtered state to both peers',async()=>{guest.send({type:'ready'});await until(()=>last(host,'lobby')?.members.find(m=>m.slot===1)?.ready,'ready');host.send({type:'start'});await until(()=>last(guest,'state')?.data.tick>5,'guest state');assert.equal(last(guest,'state').data.player,1);assert.equal(last(host,'state').data.player,0);assert.ok(!last(guest,'state').data.entities.some(e=>e.owner===0));});
 await test('Encrypted game commands reach authority with sequence acknowledgement',async()=>{const s=last(guest,'state').data,tank=s.entities.find(e=>e.owner===1&&R.D[e.type].kind==='vehicle'&&R.D[e.type].damage>0);assert.ok(tank);guest.command({type:'move',ids:[tank.id],x:120,z:65});await until(()=>last(guest,'commandResult')?.seq===1,'command acknowledgement');assert.equal(last(guest,'commandResult').result.ok,true);});
 await test('Relay payload does not contain plaintext commands, player names or snapshots',()=>{const messages=broker.messages.filter(m=>m.topic.includes('/room/'));assert.ok(messages.length>5);for(const m of messages){assert.ok(!m.payload.includes('Guest100'));assert.ok(!m.payload.includes('"entities"'));assert.ok(!m.payload.includes('"attackMove"'));}});
 await test('Late observer enters read-only delayed spectator mode',async()=>{watcher=client(url,'watch',{name:'Observer100',code:host.invite});await until(()=>watcher.spectator&&last(watcher,'spectatorWait'),'observer wait');assert.equal(watcher.command({type:'queue',unit:'grizzly'}),false);watcher.send({type:'command',seq:1,command:{type:'queue',unit:'grizzly'}});await until(()=>last(watcher,'error')?.message.includes('只读'),'server observer rejection');assert.ok(!last(watcher,'state'));});
 await test('Tampered ciphertext is rejected without applying game state',async()=>{const ch=host.channels.get(guest.peerId),before=guest.seq;broker.publish(guest.baseTopic+'/up/'+guest.peerId,JSON.stringify({s:999999,z:0,i:R.RelayCrypto.b64(new Uint8Array(12)),d:'AAAA'}));await wait(100);assert.equal(guest.seq,before);assert.ok(host.rejected>0);assert.ok(ch.rx<999999);});
 await test('Client reconnect reuses seat and synchronizes a fresh baseline',async()=>{const id=guest.token,tick=last(guest,'state').data.tick;guest.mqtt.ws.close();await until(()=>!guest.connected,'disconnect');await until(()=>guest.connected&&last(guest,'state')?.data.tick>tick,'reconnect',12000);assert.equal(guest.token,id);assert.equal(guest.player,1);guest.command({type:'stop',ids:[]});await until(()=>last(guest,'commandResult')?.seq===2,'post reconnect acknowledgement');});
 await test('Large encrypted payload fragments and reassembles completely',async()=>{const text=R.RelayCrypto.b64(crypto.getRandomValues(new Uint8Array(65000))),ch=host.channels.get(guest.peerId);host.transmit(ch,guest.baseTopic+'/down/'+guest.peerId,{type:'fixtureLarge',text});await until(()=>last(guest,'fixtureLarge'),'large fragment',10000);assert.equal(last(guest,'fixtureLarge').text,text);assert.equal(guest.fragments.size,0);});
 await test('Public directory only appears after explicit public-room creation',async()=>{const directory=client(url,'list',{}),publicHost=client(url,'create',{name:'Public100',private:false,config:{players:2}});await until(()=>publicHost.invite&&last(directory,'rooms')?.rooms.some(r=>r.name==='Public100 的房间'),'public discovery');assert.ok(last(directory,'rooms').rooms.every(r=>r.code!==host.room));directory.close();publicHost.close();});
 await test('Eight encrypted clients start and receive separately filtered player snapshots',async()=>{const h=client(url,'create',{name:'EightHost',private:true,config:{players:8,map:'basin',fogMode:'double',slots:R.defaultSlots(8,'usa')}});await until(()=>h.invite,'eight host');const guests=[];for(let i=0;i<7;i++)guests.push(client(url,'join',{name:'P'+i,nation:'russia',code:h.invite}));await until(()=>last(h,'lobby')?.members.length===8&&guests.every(g=>g.connected&&last(g,'lobby')),'eight joined',12000);for(const g of guests)g.send({type:'ready'});await until(()=>last(h,'lobby')?.members.every(m=>m.ready),'eight ready');h.send({type:'start'});await until(()=>guests.every(g=>last(g,'state')?.data.tick>=10),'eight synchronized',15000);assert.equal(new Set([h,...guests].map(c=>c.player)).size,8);for(const g of guests){assert.equal(last(g,'state').data.player,g.player);assert.ok(last(g,'state').data.entities.some(e=>e.owner===g.player));}h.close();await until(()=>guests.every(g=>!g.connected),'host closes eight room');for(const g of guests)assert.ok(last(g,'error')?.message.includes('房主已退出'));});
 await test('Host relay outage pauses simulation and resumes its original session',async()=>{const token=host.token,readBackup=()=>new Promise((resolve,reject)=>{const previous=host.worker.onmessage,timer=setTimeout(()=>{host.worker.onmessage=previous;reject(Error('backup timeout'));},3000);host.worker.onmessage=e=>{if(e.data.type==='backup'){clearTimeout(timer);host.worker.onmessage=previous;resolve(e.data.data);}else previous(e);};host.worker.postMessage({type:'backup'});});host.mqtt.ws.close();await until(()=>!host.connected,'host offline');await wait(130);const a=await readBackup();await wait(600);const b=await readBackup();assert.equal(b.tick,a.tick);assert.equal(host.command({type:'surrender'}),false);await until(()=>host.connected&&last(host,'start')?.resumed,'host resumed',10000);assert.equal(host.token,token);await until(()=>last(guest,'state')?.data.tick>b.tick,'guest after host resume',10000);assert.equal(host.player,0);});
 await test('Observer receives a snapshot no newer than 30 simulated seconds',async()=>{await until(()=>last(watcher,'state')?.data.delay>=30,'delayed snapshot',36000);const w=last(watcher,'state').data,h=last(host,'state').data;assert.ok(w.tick<=h.tick-290);assert.equal(w.spectator,true);});
 await test('Explicit host exit notifies remaining guests and cancels reconnect loops',async()=>{host.close();await until(()=>!guest.connected&&guest.intentional&&last(guest,'error')?.message.includes('房主已退出'),'explicit close');assert.equal(guest.command({type:'surrender'}),false);});
} catch(e){console.error(e.stack);console.error('HOST',host?.statusLog?.slice(-5));console.error('GUEST',guest?.statusLog?.slice(-5));}
finally{for(const c of clients)c.close();await wait(300);await broker.close();const report={version:R.VERSION,content:R.CONTENT_HASH,environment:'Node 22 native WebSocket/WebCrypto and worker_threads browser-worker adapter; loopback independent MQTT fixture, not a public broker or physical multi-device test',passed:checks.length,failed:failures.length,checks,failures};fs.writeFileSync(path.join(ROOT,'tests/mqtt-results.json'),JSON.stringify(report,null,2));console.log(`${checks.length} MQTT checks passed, ${failures.length} failed`);process.exitCode=failures.length?1:0;}
})();
