'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
require('../web/src/data.js');require('../web/src/sim.js');require('../web/src/wire.js');require('../web/src/net.js');require('../web/src/authority.js');
const R=globalThis.RA,checks=[],failures=[];const copy=o=>JSON.parse(JSON.stringify(o));
function test(name,fn){try{fn();checks.push(name);console.log('PASS',name);}catch(e){failures.push({name,error:e.stack});console.error('FAIL',name,e.message);}}
function mission(id){const s=new R.Sim(R.operationConfig(id));for(const p of s.players)p.ai=false;s.operation.nextWave=1e9;return s;}
function op(s){s.tick+=10;s.time=s.tick*R.STEP;s.tickOperation();}
function friendly(s){return s.entities.filter(e=>e.owner===0&&R.D[e.type].kind==='vehicle'&&R.D[e.type].damage>0);}
for(const def of R.OPERATIONS){
 test(`${def.id}: objective, teams, load/save and serializable player view`,()=>{const s=mission(def.id);assert.equal(s.operation.id,def.id);assert.equal(s.players[0].team,s.players[1].team);assert.notEqual(s.players[0].team,s.players[2].team);assert.ok(s.players[3].closed);const loaded=R.Sim.load(copy(s.save()));assert.deepEqual(loaded.operation,s.operation);assert.deepEqual(loaded.players,s.players);assert.equal(loaded.snapshot(1).operation.id,def.id);assert.ok(loaded.entities.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.z)));});
 test(`${def.id}: timeout is authoritative and ends the operation`,()=>{const s=mission(def.id);s.tick=s.operation.limit*10; s.time=s.operation.limit; s.tickOperation();assert.equal(s.operation.failed,true);assert.equal(s.winner,s.players[2].team);});
}
test('Allied-base loss ends mission even while enemy HQ survives',()=>{const s=mission('holdout');for(const e of s.entities)if(e.owner>=0&&s.players[e.owner].team===0)e.hp=0;op(s);assert.ok(s.operation.failed);});
test('Holdout never wins while eighth-wave enemies remain alive',()=>{const s=mission('holdout');s.operation.wave=7;s.operationWave();assert.equal(s.operation.wave,8);op(s);assert.equal(s.winner,null);for(const e of s.entities)if(e.operationUnit)e.hp=0;op(s);assert.ok(s.operation.completed);assert.equal(s.operation.stars,3);});
test('Oil control counter pauses below majority and resumes to 90',()=>{const s=mission('oil'),o=s.operation;for(const id of o.targets.slice(0,2))s.lookup.get(id).owner=0;for(let i=0;i<15;i++)op(s);assert.equal(o.progress,15);s.lookup.get(o.targets[1]).owner=-1;for(let i=0;i<10;i++)op(s);assert.equal(o.progress,15);s.lookup.get(o.targets[1]).owner=1;for(let i=0;i<75;i++)op(s);assert.ok(o.completed);assert.equal(o.progress,90);});
test('Escort waits without guards and rejects direct convoy orders',()=>{const s=mission('escort'),o=s.operation,car=s.lookup.get(o.targets[0]);for(const u of s.entities)if(u.owner>=0&&s.players[u.owner].team===0&&['infantry','vehicle'].includes(R.D[u.type].kind)&&R.D[u.type].damage>0){u.x=175;u.z=175;}op(s);assert.equal(o.escortPresent,false);assert.equal(car.order,null);assert.equal(s.command(0,{type:'move',ids:[car.id],x:100,z:100}).ok,false);const g=friendly(s)[0];g.x=car.x+2;g.z=car.z;op(s);assert.equal(o.escortPresent,true);assert.equal(car.order.type,'move');});
test('Escort has five real waypoint tests and convoy destruction fails',()=>{const s=mission('escort'),o=s.operation,car=s.lookup.get(o.targets[0]);for(const point of o.route){car.x=point.x;car.z=point.z;op(s);}assert.ok(o.completed);assert.equal(o.progress,5);const t=mission('escort');t.lookup.get(t.operation.targets[0]).hp=0;op(t);assert.ok(t.operation.failed);});
test('Blackout requires every radar, supports capture as well as destruction',()=>{const s=mission('blackout'),o=s.operation;s.lookup.get(o.targets[0]).hp=0;s.lookup.get(o.targets[1]).owner=1;op(s);assert.equal(o.progress,2);assert.equal(s.winner,null);s.lookup.get(o.targets[2]).hp=0;op(s);assert.ok(o.completed);});
test('Siege cannot win only by destroying the ordinary enemy HQ',()=>{const s=mission('siege');for(const e of s.own(2,'hq'))e.hp=0;op(s);assert.equal(s.winner,null);s.lookup.get(s.operation.targets[0]).hp=0;op(s);assert.ok(s.operation.completed);});
test('Extraction requires physical rescue, clear extraction area and guards',()=>{const s=mission('extraction'),o=s.operation,g=friendly(s)[0];for(const id of o.targets){const e=s.lookup.get(id);g.x=e.x+1;g.z=e.z;op(s);}assert.equal(o.rescued.length,3);assert.equal(s.winner,null);for(const g of friendly(s)){g.x=o.extraction.x;g.z=o.extraction.z;}const enemy=s.spawn('rhino',2,o.extraction.x+3,o.extraction.z);op(s);assert.equal(o.hold,0);enemy.hp=0;for(let i=0;i<30;i++)op(s);assert.ok(o.completed);});
test('Extraction fails if an unrescued squad is destroyed',()=>{const s=mission('extraction');s.lookup.get(s.operation.targets[0]).hp=0;op(s);assert.ok(s.operation.failed);});
test('Objective cadence is exactly once per second and is preserved after load',()=>{const s=mission('oil');for(const id of s.operation.targets)s.lookup.get(id).owner=0;op(s);s.tickOperation();assert.equal(s.operation.progress,1);const t=R.Sim.load(copy(s.save()));t.tickOperation();assert.equal(t.operation.progress,1);op(t);assert.equal(t.operation.progress,2);});
test('Operation score is based on time and losses, not a guaranteed three-star badge',()=>{const s=mission('blackout');s.players[0].lost=30;s.tick=4000;s.time=400;for(const id of s.operation.targets)s.lookup.get(id).hp=0;s.tickOperation();assert.equal(s.operation.stars,1);});
test('Mission data rejects unknown identifiers and oversized target lists',()=>{const save=mission('holdout').save();save.operation.id='other';assert.throws(()=>R.Sim.load(save));save.operation.id='holdout';save.operation.targets=Array(13).fill(1);assert.throws(()=>R.Sim.load(save));});
test('Replay v2 checkpoints preserve simulation and seek from nearest full state',()=>{const s=new R.Sim({players:2,sandbox:true,seed:873,fogMode:'double'});for(let i=0;i<1350;i++)s.tickStep();const r=s.exportReplay();assert.equal(r.format,'ra3d-replay-v2');assert.equal(r.checkpoints.length,2);const replay=new R.Replay(copy(r));replay.seek(1290);assert.equal(replay.seekOrigin,1200);const compare=R.Sim.load(copy(r.initial));compare._recording=false;for(let i=0;i<1290;i++)compare.tickStep();assert.deepEqual(replay.sim.save(),compare.save());replay.seek(200);assert.equal(replay.seekOrigin,0);assert.equal(replay.sim.tick,200);});
test('Operation replay seeks across checkpoint with matching objectives and entities',()=>{const s=mission('oil');s._initialSave=copy(s.save());for(let i=0;i<680;i++)s.tickStep();const r=new R.Replay(s.exportReplay());r.seek(670);const t=R.Sim.load(copy(r.data.initial));t._recording=false;for(let i=0;i<670;i++)t.tickStep();assert.deepEqual(r.sim.operation,t.operation);assert.deepEqual(r.sim.entities,t.entities);});
test('Replay rejects forged checkpoint times and journal offsets',()=>{const s=new R.Sim({players:2,sandbox:true});for(let i=0;i<601;i++)s.tickStep();let r=s.exportReplay();r.checkpoints[0].tick=599;assert.throws(()=>new R.Replay(r));r=s.exportReplay();r.checkpoints[0].index=999;assert.throws(()=>new R.Replay(r));});
function peer(service,id){const messages=[];let p;const ws={readyState:1,bufferedAmount:0,ip:id,send:v=>messages.push(JSON.parse(v)),close(){ws.readyState=3;if(p)service.left(p);}};p=service.add(ws);return {p,messages,send:m=>service.handle(p,{...R.netIdentity(),...m}),last:t=>messages.filter(m=>m.type===t).at(-1)};}
test('Cooperative authority reserves two human seats and starts correct mission rules',()=>{const a=new R.RoomService(),host=peer(a,'h'),guest=peer(a,'g'),third=peer(a,'x');host.send({type:'create',config:R.operationConfig('oil'),nation:'usa'});const code=host.last('welcome').code;guest.send({type:'join',code});third.send({type:'join',code});assert.ok(third.last('error'));guest.send({type:'ready'});host.send({type:'start'});const room=a.rooms.get(code);assert.ok(room.started);assert.equal(room.sim.operation.id,'oil');assert.equal(room.sim.players[0].team,room.sim.players[1].team);assert.equal(room.members.size,2);});
test('Spectator is capped, delayed, cannot chat or send commands and can resume',()=>{const a=new R.RoomService(),h=peer(a,'h');h.send({type:'create',config:{players:2}});const code=h.last('welcome').code;h.send({type:'start'});let first;for(let i=0;i<5;i++){const w=peer(a,'w'+i);w.send({type:'watch',code});if(!i)first=w;if(i<4)assert.equal(w.last('welcome').spectator,true);else assert.ok(w.last('error'));}first.send({type:'command',seq:1,command:{type:'surrender'}});assert.match(first.last('error').message,/只读/);first.send({type:'chat',text:'secret'});assert.match(first.last('error').message,/只读/);assert.ok(!first.last('state'));for(let i=0;i<330;i++){a.advance();a.flush();}const state=first.last('state');assert.ok(state);assert.ok(state.data.tick<=a.rooms.get(code).sim.tick-300);const token=first.last('welcome').token;first.p.ws.close();const resume=peer(a,'w-r');resume.send({type:'resume',code,token});assert.equal(resume.last('welcome').spectator,true);});
test('Shared authority enforces message byte ceiling, not just the Node WS wrapper',()=>{const a=new R.RoomService(),p=peer(a,'large');p.send({type:'ping',at:'A'.repeat(20000)});assert.match(p.last('error').message,/16KB/);assert.equal(p.last('pong'),undefined);});
test('Friendly mission AI escorts the convoy rather than scouting unrelated HQs',()=>{const s=mission('escort'),p=s.players[1];p.ai=true;s.operationAllyAI(p);const car=s.lookup.get(s.operation.targets[0]),army=s.own(1).filter(e=>e.order?.type==='attackMove');assert.ok(army.length>=2);assert.ok(army.some(e=>Math.hypot(e.order.x-car.x,e.order.z-car.z)<10));assert.equal(s._journal.length,0);});
test('Friendly mission engineers receive capture orders for briefing-marked oil',()=>{const s=mission('oil'),p=s.players[1];p.ai=true;s.operationAllyAI(p);const e=s.own(1).find(e=>R.D[e.type].ability==='engineer');assert.equal(e.order.type,'move');const t=s.lookup.get(s.operation.targets[0]);e.x=t.x+3;e.z=t.z;s.updateFog();s.operationAllyAI(p);assert.equal(e.order.type,'capture');});
require('../web/src/geometry.js');require('../web/src/art.js');require('../web/src/art-expanded.js');
test('All 129 detailed model variants contain only finite triangles within budgets',()=>{let detailed=0;for(const d of R.defs()){const m=R.makeModel(d);if(m.detail)detailed++;let n=0;for(const g of [m.body,m.turret,m.detail,m.turretDetail,...(m.parts||[]).map(p=>p.geo)].filter(Boolean)){assert.ok(g.v.every(Number.isFinite),d.id);assert.equal(g.v.length%30,0);n+=g.v.length/30;}assert.ok(n<3000,d.id);}assert.equal(detailed,116);});
fs.writeFileSync(__dirname+'/release-results.json',JSON.stringify({version:R.VERSION,content:R.CONTENT_HASH,passed:checks.length,failed:failures.length,environment:'Node deterministic objective fixtures and shared authority tests; objective success fixtures are not human difficulty/playthrough validation',checks,failures},null,2));console.log(`${checks.length} release checks passed, ${failures.length} failed`);process.exitCode=failures.length?1:0;
