'use strict';
const assert=require('node:assert/strict');
require('../web/src/data.js');const Sim=require('../web/src/sim.js');const R=globalThis.RA;
let passed=0;const results=[];
function test(name,fn){const t=performance.now();try{fn();const ms=+(performance.now()-t).toFixed(2);results.push({name,passed:true,ms});console.log('PASS',name,ms+'ms');passed++;}catch(e){console.error('FAIL',name,e);process.exitCode=1;results.push({name,passed:false,error:e.message});}}
const step=(s,n)=>{for(let i=0;i<n;i++)s.tickStep();};
const sandbox=(nation='usa')=>new Sim({players:2,sandbox:true,reveal:true,nation,map:'basin'});
function refresh(s){s.reindex();s.rebuildGrid();s.updatePower();s.updateFog();s.pathBudget=100;}
function only(s,types){s.entities=s.entities.filter(e=>types.includes(e.type));refresh(s);}
test('10 nations and all catalog definitions have finite core data',()=>{assert.equal(R.NATIONS.length,10);for(const d of R.defs()){assert.ok(d.id&&d.name&&Number.isFinite(d.hp)&&d.hp>0);assert.ok(Number.isFinite(d.cost));for(const req of d.requires)assert.equal(typeof req,'string');}});
test('All nation starts: eight seats, headquarters and worker',()=>{for(const n of R.NATIONS){const s=new Sim({nation:n.id});assert.equal(s.players.length,8);assert.equal(s.players[0].nation,n.id);assert.ok(s.has(0,'hq'));assert.ok(s.own(0).some(e=>R.D[e.type].ability==='miner'));step(s,15);assert.equal(s.tick,15);}});
test('Real economy: ore depletion and deposited credits',()=>{const s=sandbox(),before=s.ores.reduce((n,o)=>n+o.amount,0),credits=s.players[0].credits;step(s,600);assert.ok(s.players[0].earned>0);assert.ok(s.players[0].credits>credits);assert.ok(s.ores.reduce((n,o)=>n+o.amount,0)<before);});
test('Production, placement validation and factory spawn',()=>{const s=sandbox(),p=s.players[0];assert.equal(s.command(0,{type:'queue',unit:'a_factory'}).ok,true);step(s,90);assert.equal(p.ready.type,'a_factory');assert.equal(s.command(0,{type:'place',x:190,z:190}).ok,false);assert.equal(s.command(0,{type:'place',x:50,z:154}).ok,true);refresh(s);const before=s.own(0).filter(e=>e.type==='grizzly').length;assert.ok(s.command(0,{type:'queue',unit:'grizzly'}).ok);step(s,60);assert.equal(s.own(0).filter(e=>e.type==='grizzly').length,before+1);assert.ok(s.entities.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.z)));});
test('Production cancel refunds exactly before simulation',()=>{const s=sandbox(),p=s.players[0],before=p.credits;assert.ok(s.command(0,{type:'queue',unit:'a_power'}).ok);assert.equal(p.credits,before-R.D.a_power.cost);s.command(0,{type:'cancel',category:'building',unit:'a_power'});assert.equal(p.credits,before);assert.equal(p.queues.building.length,0);});
test('MCV deployment with no initial headquarters',()=>{const s=new Sim({players:2,startBase:false,sandbox:true,nation:'yuri'});assert.equal(s.has(0,'hq'),false);const m=s.own(0).find(e=>R.D[e.type].ability==='mcv');assert.ok(s.command(0,{type:'deploy',ids:[m.id]}).ok);assert.equal(m.type,'y_hq');assert.ok(s.has(0,'hq'));});
test('Ownership enforcement and sandbox authorization',()=>{const s=new Sim({players:2}),enemy=s.own(1).find(e=>R.D[e.type].kind==='vehicle');assert.equal(s.command(0,{type:'move',ids:[enemy.id],x:95,z:95}).ok,false);assert.equal(s.command(0,{type:'sandbox',action:'credits'}).ok,false);assert.equal(s.command(0,{type:'place',x:NaN,z:0}).ok,false);assert.equal(s.command(0,{type:'queue',unit:'sniper'}).ok,false);});
test('Fog-filtered client state does not expose remote enemy army',()=>{const s=new Sim({players:8});const snap=s.snapshot(0);assert.ok(snap.entities.length<s.entities.length);assert.ok(!snap.entities.some(e=>e.owner===4));assert.equal(snap.fog.length,4096);});
test('Path following actually moves land units',()=>{const s=sandbox(),tank=s.own(0).find(e=>e.type==='grizzly');const x=tank.x,z=tank.z;assert.ok(s.command(0,{type:'move',ids:[tank.id],x:60,z:164}).ok);step(s,120);assert.ok(Math.hypot(tank.x-x,tank.z-z)>8);assert.ok(Math.hypot(tank.x-60,tank.z-164)<8);});
test('Mind control ownership, controller death and overload',()=>{const s=sandbox('yuri');s.entities=[];refresh(s);const y=s.spawn('yuri_clone',0,60,60),t=s.spawn('grizzly',1,64,60);refresh(s);step(s,12);assert.equal(t.owner,0);assert.equal(t.controlledBy,y.id);s.damage(y,99999,null,'blast');assert.equal(t.owner,1);const m=s.spawn('mastermind',0,100,100);for(let i=0;i<4;i++)s.spawn('grizzly',0,100+i*3,105,{controlledBy:m.id,originalOwner:1});refresh(s);const hp=m.hp;step(s,10);assert.ok(m.hp<hp);});
test('Engineer captures neutral oil and generates income',()=>{const s=sandbox(),oil=s.entities.find(e=>e.type==='oil');const eng=s.spawn('a_engineer',0,oil.x+4,oil.z);refresh(s);assert.ok(s.command(0,{type:'target',ids:[eng.id],target:oil.id}).ok);step(s,20);assert.equal(oil.owner,0);const earn=s.players[0].earned;step(s,20);assert.ok(s.players[0].earned>earn);});
test('Neutral garrison, unloading and transport vehicle passengers',()=>{const s=sandbox(),b=s.spawn('civ_building',-1,74,90);refresh(s);const inf=s.spawn('gi',0,b.x+4,b.z);refresh(s);assert.ok(s.command(0,{type:'target',ids:[inf.id],target:b.id}).ok);step(s,10);assert.equal(inf.inside,b.id);assert.equal(b.owner,0);s.command(0,{type:'unload',ids:[b.id]});step(s,1);assert.ok(!inf.inside);assert.equal(b.owner,-1);const tr=s.spawn('a_transport',0,85,140),tank=s.spawn('grizzly',0,88,140);refresh(s);s.command(0,{type:'target',ids:[tank.id],target:tr.id});step(s,10);assert.equal(tank.inside,tr.id);});
test('Superweapon damages targets and consumes charge',()=>{const s=sandbox('russia');s.entities=[];const n=s.spawn('s_nuke',0,50,50,{charge:999}),power=s.spawn('s_nuclear',0,60,50);const target=s.spawn('a_factory',1,100,100);refresh(s);const hp=target.hp;assert.ok(s.command(0,{type:'super',ability:'nuke',x:100,z:100}).ok);assert.ok(target.hp<hp);assert.equal(n.charge,0);});
test('Save/load fixed-state consistency and continuing simulation',()=>{const s=sandbox();step(s,150);const json=JSON.stringify(s.save()),clone=Sim.load(JSON.parse(json));assert.equal(clone.tick,s.tick);assert.equal(clone.entities.length,s.entities.length);assert.equal(clone.players[0].credits,s.players[0].credits);step(s,60);step(clone,60);assert.deepEqual(clone.entities.map(e=>[e.id,e.x,e.z,e.hp]),s.entities.map(e=>[e.id,e.x,e.z,e.hp]));assert.equal(clone.seed,s.seed);});
test('Seed determinism: independent eight-seat simulation',()=>{const a=new Sim(),b=new Sim();step(a,400);step(b,400);assert.equal(JSON.stringify(a.save()),JSON.stringify(b.save()));});
test('Victory and surrender reach a result',()=>{const s=new Sim({players:2});assert.ok(s.command(1,{type:'surrender'}).ok);assert.equal(s.winner,0);});
test('Sandbox AI switch and vacant host slot',()=>{const s=sandbox();assert.equal(!!s.cfg.sandboxAI,false);s.command(0,{type:'sandbox',action:'ai'});assert.ok(s.cfg.sandboxAI);assert.ok(s.players[1].ai);s.command(0,{type:'sandbox',action:'ai'});assert.equal(s.cfg.sandboxAI,false);const m=new Sim({players:2,slots:[{human:false},{human:true}]});assert.ok(m.players[0].ai);assert.equal(m.players[1].ai,false);});
test('Every catalog definition can run in an isolated sandbox',()=>{for(const d of R.defs()){const s=sandbox(d.faction==='yuri'?'yuri':d.faction==='soviet'?'russia':'usa');s.entities=[];refresh(s);const e=s.spawn(d.id,0,80,80);refresh(s);step(s,6);assert.ok(Number.isFinite(e.hp),d.id);assert.ok(Number.isFinite(e.x),d.id);}});
test('Eight-seat 600-second match with finite state and AI combat',()=>{const s=new Sim();step(s,6000);assert.ok(s.entities.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.x)&&Number.isFinite(e.z)));assert.ok(s.players.reduce((n,p)=>n+p.kills,0)>0);assert.ok(s.players.some(p=>p.lost>0));console.log('  Match:',s.time.toFixed(1)+' sim seconds,',s.entities.length,'entities,',s.players.reduce((n,p)=>n+p.kills,0),'kills, winner',s.winner);});
console.log(`\n${passed}/${results.length} checks passed`);
if(process.argv.includes('--json'))require('node:fs').writeFileSync(require('node:path').join(__dirname,'sim-results.json'),JSON.stringify({version:R.VERSION,runtime:process.version,date:new Date().toISOString(),passed,total:results.length,results},null,2));
